import type { ProviderManifest } from '../../types.js';

export const resendManifest: ProviderManifest = {
  name: 'resend',
  displayName: 'Resend',
  detect: {
    packages: ['resend'],
    imports: ['resend'],
    urlPatterns: ['api.resend.com'],
  },
  surface: {
    packages: ['resend'],
    clientConstructors: ['Resend'],
    clientNamePattern: /^resend([-_]?client)?$/i,
    docsUrl: 'https://resend.com/docs/api-reference/introduction',
    // The SDK revision this surface was last read against by hand. Bump both
    // together, only after re-reading the diff — `pnpm sdk:watch` lists every
    // source commit landed since `commit`, including the logic changes that
    // leave the method list untouched.
    verified: {
      version: '6.20.0',
      commit: '5bc4c27d9bedb0f7288609a8d3e1c16adc3ad7e7',
      at: '2026-08-19',
      sourceDir: 'src',
    },
    // Verified against resend@6.20.0 dist/index.d.mts resource classes and
    // cross-checked against Resend's OpenAPI spec (openapi_resend.yaml in
    // this directory): every spec endpoint maps to a method below. Four
    // entries are SDK-side extras with no 1:1 endpoint, all present in the
    // SDK types: emails.create/batch.create (documented aliases of
    // emails.send/batch.send), webhooks.verify (local signature helper),
    // and emails.receiving.forward (in the SDK, not yet in the spec copy).
    // Added since 6.18.0, both plain additions read from the SDK source:
    // broadcasts.cancel (6.19.0, POST /broadcasts/{id}/cancel) and
    // automations.duplicate (6.20.0, POST /automations/{id}/duplicate).
    // `audiences` is a deprecated alias of Segments kept because real code
    // still uses it (Audiences→Segments docs migration is in progress) —
    // re-verify this list on Resend SDK majors (`pnpm check:surface`).
    methods: [
      'apiKeys.create',
      'apiKeys.list',
      'apiKeys.remove',
      'audiences.create',
      'audiences.get',
      'audiences.list',
      'audiences.remove',
      'automations.create',
      'automations.duplicate',
      'automations.get',
      'automations.list',
      'automations.remove',
      'automations.runs.get',
      'automations.runs.list',
      'automations.stop',
      'automations.update',
      'batch.create',
      'batch.send',
      'broadcasts.cancel',
      'broadcasts.create',
      'broadcasts.get',
      'broadcasts.list',
      'broadcasts.remove',
      'broadcasts.send',
      'broadcasts.update',
      'contactProperties.create',
      'contactProperties.get',
      'contactProperties.list',
      'contactProperties.remove',
      'contactProperties.update',
      'contacts.create',
      'contacts.get',
      'contacts.imports.create',
      'contacts.imports.get',
      'contacts.imports.list',
      'contacts.list',
      'contacts.remove',
      'contacts.segments.add',
      'contacts.segments.list',
      'contacts.segments.remove',
      'contacts.topics.list',
      'contacts.topics.update',
      'contacts.update',
      'domains.claims.create',
      'domains.claims.get',
      'domains.claims.verify',
      'domains.create',
      'domains.get',
      'domains.list',
      'domains.remove',
      'domains.update',
      'domains.verify',
      'emails.attachments.get',
      'emails.attachments.list',
      'emails.cancel',
      'emails.create',
      'emails.get',
      'emails.list',
      'emails.receiving.attachments.get',
      'emails.receiving.attachments.list',
      'emails.receiving.forward',
      'emails.receiving.get',
      'emails.receiving.list',
      'emails.send',
      'emails.update',
      'events.create',
      'events.get',
      'events.list',
      'events.remove',
      'events.send',
      'events.update',
      'logs.get',
      'logs.list',
      'oauthGrants.list',
      'oauthGrants.revoke',
      'segments.create',
      'segments.get',
      'segments.list',
      'segments.remove',
      'suppressions.add',
      'suppressions.batch.add',
      'suppressions.batch.remove',
      'suppressions.get',
      'suppressions.list',
      'suppressions.remove',
      'templates.create',
      'templates.duplicate',
      'templates.get',
      'templates.list',
      'templates.publish',
      'templates.remove',
      'templates.update',
      'topics.create',
      'topics.get',
      'topics.list',
      'topics.remove',
      'topics.update',
      'webhooks.create',
      'webhooks.get',
      'webhooks.list',
      'webhooks.remove',
      'webhooks.update',
      'webhooks.verify',
    ],
  },
  rules: [
    {
      key: 'resend-webhook-signature',
      resultRule: 'resend/webhook-signature-missing',
      message:
        'This webhook handler appears to process Resend events without verifying the webhook signature.',
      fix: 'Verify incoming webhooks with Svix (Resend uses Svix signatures). Validate headers and payload before handling events.',
      docsUrl: 'https://resend.com/docs/webhooks/verify-webhooks-requests',
      severity: 'error',
    },
    // RULE-DISABLED 2026-07-28 (pre-launch): overfitting, 46/47 (98%) false
    // positives in review. Rule, tests and fixtures are intact.
    // NOTE: tests/fixtures/resend/docs-examples/send-batch.ts had this rule in
    // its `docs-example-expected` list; that entry is commented out there too
    // and must be restored in the same change that re-enables this rule.
    // {
    //   key: 'resend-api-key-hardcoded',
    //   resultRule: 'resend/security/api-key-hardcoded',
    //   message: 'Hardcoded Resend API key found in source code.',
    //   fix: 'Move the key to an environment variable and read it via process.env.RESEND_API_KEY.',
    //   docsUrl: 'https://resend.com/docs/send-with-nextjs#prerequisites',
    //   severity: 'error',
    // },
    {
      key: 'resend-api-key-in-client-bundle',
      resultRule: 'resend/security/api-key-in-client-bundle',
      message: 'Resend SDK imported into client-bundled code, which can leak the API key.',
      fix: 'Import and use Resend only in server code (route handlers, server actions, server components).',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'error',
    },
    {
      key: 'resend-marketing-via-batch-send',
      resultRule: 'resend/correctness/marketing-via-batch-send',
      message: 'Marketing email sent via resend.batch.send instead of the Broadcasts API.',
      fix: 'Use the Broadcasts API (resend.broadcasts.*) or the Dashboard Broadcasts workflow for marketing sends.',
      docsUrl: 'https://resend.com/docs/dashboard/emails/batch-sending',
      severity: 'error',
    },
    {
      key: 'resend-marketing-missing-unsubscribe',
      resultRule: 'resend/correctness/marketing-missing-unsubscribe',
      message: 'Marketing email has no unsubscribe mechanism.',
      fix: 'Add a List-Unsubscribe header (RFC 8058) or include {{{RESEND_UNSUBSCRIBE_URL}}} in the HTML, or send via Broadcasts.',
      docsUrl: 'https://resend.com/docs/dashboard/broadcasts/introduction',
      severity: 'error',
    },
    {
      key: 'resend-test-domain-in-production-path',
      resultRule: 'resend/correctness/test-domain-in-production-path',
      message: 'Test-only sender onboarding@resend.dev used in production code.',
      fix: 'Send from a verified domain configured via process.env.RESEND_FROM_EMAIL.',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'warning',
    },
    {
      key: 'resend-from-address-not-friendly-format',
      resultRule: 'resend/reliability/from-address-not-friendly-format',
      message: 'From address is a bare email rather than the "Name <email>" format.',
      fix: 'Use a friendly-name sender, e.g. "Acme <onboarding@acme.com>".',
      docsUrl: 'https://resend.com/docs/api-reference/emails/send-email',
      severity: 'info',
    },
    {
      key: 'resend-batch-size-not-enforced',
      resultRule: 'resend/reliability/batch-size-not-enforced',
      message: 'resend.batch.send called without enforcing the 100-email limit.',
      fix: 'Guard the array length (max 100) before calling batch.send, or chunk the array.',
      docsUrl: 'https://resend.com/docs/api-reference/emails/send-batch-emails',
      severity: 'warning',
    },
    {
      key: 'resend-missing-idempotency-key',
      resultRule: 'resend/reliability/missing-idempotency-key',
      message: 'Resend send/batch call has no idempotencyKey.',
      fix: 'Pass an idempotencyKey (e.g. welcome/${userId}) to prevent duplicate sends on retry.',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'warning',
    },
    {
      key: 'resend-unchecked-send-error',
      resultRule: 'resend/correctness/unchecked-send-error',
      message: 'Resend call never checks the returned error — the SDK does not throw.',
      fix: 'Bind the result and check it: const { data, error } = await resend.emails.send(...); if (error) throw new Error(error.message);',
      docsUrl: 'https://resend.com/docs/api-reference/errors',
      severity: 'error',
    },
    {
      key: 'resend-no-error-code-mapping',
      resultRule: 'resend/reliability/no-error-code-mapping',
      message: 'Resend errors are returned as a blanket HTTP 500.',
      fix: 'Map Resend error codes (400/401/403/422/429) to appropriate HTTP statuses instead of always 500.',
      docsUrl: 'https://resend.com/docs/ai-onboarding',
      severity: 'warning',
    },
    {
      key: 'resend-webhook-no-idempotency',
      resultRule: 'resend/reliability/webhook-no-idempotency',
      message: 'Resend webhook handler does not deduplicate retried events.',
      fix: 'Track processed event ids (e.g. event.data.email_id) in a store or set, since Resend retries for 24h.',
      docsUrl: 'https://resend.com/docs/webhooks/introduction',
      severity: 'warning',
    },
    {
      key: 'resend-missing-tags',
      resultRule: 'resend/reliability/missing-tags',
      message: 'Resend send has no tags for deliverability segmentation.',
      fix: 'Add tags, e.g. tags: [{ name: "category", value: "welcome" }].',
      docsUrl: 'https://resend.com/docs/dashboard/emails/tags',
      severity: 'info',
    },
    {
      key: 'resend-request-id-not-logged',
      resultRule: 'resend/reliability/request-id-not-logged',
      message: 'Resend error handler does not log the request id.',
      fix: 'Log error.headers?.["x-request-id"] (or x-resend-request-id) alongside error.message.',
      docsUrl: 'https://resend.com/docs/api-reference/errors',
      severity: 'info',
    },
  ],
};
