import type { ProviderManifest } from '../../types.js';

export const resendManifest: ProviderManifest = {
  name: 'resend',
  displayName: 'Resend',
  detect: {
    packages: ['resend'],
    imports: ['resend'],
    urlPatterns: ['api.resend.com'],
  },
  oxlintRules: [
    {
      key: 'resend-webhook-signature',
      resultRule: 'resend/webhook-signature-missing',
      message:
        'This webhook handler appears to process Resend events without verifying the webhook signature.',
      fix: 'Verify incoming webhooks with Svix (Resend uses Svix signatures). Validate headers and payload before handling events.',
      docsUrl: 'https://resend.com/docs/dashboard/webhooks/introduction#verify-webhook-signatures',
      severity: 'error',
    },
    {
      key: 'resend-api-key-hardcoded',
      resultRule: 'resend/security/api-key-hardcoded',
      message: 'Hardcoded Resend API key found in source code.',
      fix: 'Move the key to an environment variable and read it via process.env.RESEND_API_KEY.',
      docsUrl: 'https://resend.com/docs/send-with-nextjs#prerequisites',
      severity: 'error',
    },
    {
      key: 'resend-api-key-in-client-bundle',
      resultRule: 'resend/security/api-key-in-client-bundle',
      message: 'Resend SDK imported into client-bundled code, which can leak the API key.',
      fix: 'Import and use Resend only in server code (route handlers, server actions, server components).',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'error',
    },
    {
      key: 'resend-marketing-via-batch-send',
      resultRule: 'resend/correctness/marketing-via-batch-send',
      message: 'Marketing email sent via resend.batch.send instead of the Broadcasts API.',
      fix: 'Use the Broadcasts API (resend.broadcasts.*) or the Dashboard Broadcasts workflow for marketing sends.',
      docsUrl: 'https://resend.com/docs/dashboard/emails/batch-sending',
      severity: 'error',
    },
    {
      key: 'resend-marketing-missing-unsubscribe',
      resultRule: 'resend/correctness/marketing-missing-unsubscribe',
      message: 'Marketing email has no unsubscribe mechanism.',
      fix: 'Add a List-Unsubscribe header (RFC 8058) or include {{{RESEND_UNSUBSCRIBE_URL}}} in the HTML, or send via Broadcasts.',
      docsUrl: 'https://resend.com/docs/dashboard/broadcasts/introduction',
      severity: 'error',
    },
    {
      key: 'resend-test-domain-in-production-path',
      resultRule: 'resend/correctness/test-domain-in-production-path',
      message: 'Test-only sender onboarding@resend.dev used in production code.',
      fix: 'Send from a verified domain configured via process.env.RESEND_FROM_EMAIL.',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'warning',
    },
    {
      key: 'resend-from-address-not-friendly-format',
      resultRule: 'resend/integration/from-address-not-friendly-format',
      message: 'From address is a bare email rather than the "Name <email>" format.',
      fix: 'Use a friendly-name sender, e.g. "Acme <onboarding@acme.com>".',
      docsUrl: 'https://resend.com/docs/api-reference/emails/send-email',
      severity: 'info',
    },
    {
      key: 'resend-batch-size-not-enforced',
      resultRule: 'resend/reliability/batch-size-not-enforced',
      message: 'resend.batch.send called without enforcing the 100-email limit.',
      fix: 'Guard the array length (max 100) before calling batch.send, or chunk the array.',
      docsUrl: 'https://resend.com/docs/api-reference/emails/send-batch-emails',
      severity: 'warning',
    },
    {
      key: 'resend-missing-idempotency-key',
      resultRule: 'resend/reliability/missing-idempotency-key',
      message: 'Resend send/batch call has no idempotencyKey.',
      fix: 'Pass an idempotencyKey (e.g. welcome/${userId}) to prevent duplicate sends on retry.',
      docsUrl: 'https://resend.com/docs/send-with-nextjs',
      severity: 'warning',
    },
    {
      key: 'resend-no-error-code-mapping',
      resultRule: 'resend/reliability/no-error-code-mapping',
      message: 'Resend errors are returned as a blanket HTTP 500.',
      fix: 'Map Resend error codes (400/401/403/422/429) to appropriate HTTP statuses instead of always 500.',
      docsUrl: 'https://resend.com/docs/ai-onboarding',
      severity: 'warning',
    },
    {
      key: 'resend-webhook-no-idempotency',
      resultRule: 'resend/reliability/webhook-no-idempotency',
      message: 'Resend webhook handler does not deduplicate retried events.',
      fix: 'Track processed event ids (e.g. event.data.email_id) in a store or set, since Resend retries for 24h.',
      docsUrl: 'https://resend.com/docs/dashboard/webhooks/introduction',
      severity: 'warning',
    },
    {
      key: 'resend-missing-tags',
      resultRule: 'resend/integration/missing-tags',
      message: 'Resend send has no tags for deliverability segmentation.',
      fix: 'Add tags, e.g. tags: [{ name: "category", value: "welcome" }].',
      docsUrl: 'https://resend.com/docs/dashboard/emails/tags',
      severity: 'info',
    },
    {
      key: 'resend-request-id-not-logged',
      resultRule: 'resend/integration/request-id-not-logged',
      message: 'Resend error handler does not log the request id.',
      fix: 'Log error.headers?.["x-request-id"] (or x-resend-request-id) alongside error.message.',
      docsUrl: 'https://resend.com/docs/api-reference/errors',
      severity: 'info',
    },
  ],
};
