import type { ProviderManifest } from '../../types.js';

export const openaiManifest: ProviderManifest = {
  name: 'openai',
  displayName: 'OpenAI',
  detect: {
    packages: ['openai'],
    imports: ['openai'],
    urlPatterns: ['api.openai.com'],
  },
  surface: {
    packages: ['openai'],
    // All three are exported from the package root and extend the same OpenAI
    // client (azure.d.ts / bedrock.d.ts), so they share this resource surface.
    clientConstructors: ['OpenAI', 'AzureOpenAI', 'BedrockOpenAI'],
    clientNamePattern: /^(openai([-_]?client)?|oai)$/i,
    docsUrl: 'https://developers.openai.com/api/reference/overview',
    // Verified against openai@7.2.0 type declarations (client.d.ts root class +
    // resources/**/*.d.ts — multi-file Stainless layout) and cross-checked
    // against the SDK's own method↔endpoint catalog (api.md plus the
    // conversations/realtime/responses/webhooks sub-catalogs in
    // openai/openai-node@master): every endpoint-backed catalog entry maps to a
    // method below. SDK-side extras with no 1:1 endpoint, all kept:
    //   - documented polling/upload/streaming helpers the catalog itself lists
    //     without endpoints (beta.threads.* *Poll/*Stream variants,
    //     files.waitForProcessing, vectorStores.* poll/upload/createAndPoll
    //     variants, webhooks.unwrap);
    //   - chat.completions.parse/runTools/stream and responses.parse/stream —
    //     documented structured-output/streaming helpers over the create
    //     endpoints;
    //   - webhooks.verifySignature — local HMAC verification, no HTTP call;
    //   - beta.realtime.sessions.create and
    //     beta.realtime.transcriptionSessions.create — deprecated beta Realtime
    //     REST endpoints still shipped in the types (real code still calls them).
    // The graders root resource contributes nothing: GraderModels is a
    // types-only container with no callable methods. Transport escape hatches
    // (get/post/put/patch/delete/request) are deliberately excluded — calls to
    // them land in unknown_sdk_calls. The OpenAI Agents SDK (@openai/agents,
    // @openai/agents-core, @openai/agents-openai) is deliberately out of scope:
    // its API is free functions and constructions (run(agent, input), tool(),
    // new Agent(...)) with no client root the collector could attribute calls
    // to — only Runner.run would qualify, which would misrepresent the SDK
    // (same reasoning as Stagehand for browserbase and firebase's modular free
    // functions). @openai/agents-realtime belongs to the openai-realtime
    // provider and is likewise excluded here. Calls on excluded packages never
    // reach this surface; they are simply not collected (their clients are not
    // verified), not counted as unknown. Re-verify on SDK majors
    // (`pnpm check:surface`).
    methods: [
      'admin.organization.adminAPIKeys.create',
      'admin.organization.adminAPIKeys.delete',
      'admin.organization.adminAPIKeys.list',
      'admin.organization.adminAPIKeys.retrieve',
      'admin.organization.auditLogs.list',
      'admin.organization.certificates.activate',
      'admin.organization.certificates.create',
      'admin.organization.certificates.deactivate',
      'admin.organization.certificates.delete',
      'admin.organization.certificates.list',
      'admin.organization.certificates.retrieve',
      'admin.organization.certificates.update',
      'admin.organization.dataRetention.retrieve',
      'admin.organization.dataRetention.update',
      'admin.organization.groups.create',
      'admin.organization.groups.delete',
      'admin.organization.groups.list',
      'admin.organization.groups.retrieve',
      'admin.organization.groups.roles.create',
      'admin.organization.groups.roles.delete',
      'admin.organization.groups.roles.list',
      'admin.organization.groups.roles.retrieve',
      'admin.organization.groups.update',
      'admin.organization.groups.users.create',
      'admin.organization.groups.users.delete',
      'admin.organization.groups.users.list',
      'admin.organization.groups.users.retrieve',
      'admin.organization.invites.create',
      'admin.organization.invites.delete',
      'admin.organization.invites.list',
      'admin.organization.invites.retrieve',
      'admin.organization.projects.apiKeys.delete',
      'admin.organization.projects.apiKeys.list',
      'admin.organization.projects.apiKeys.retrieve',
      'admin.organization.projects.archive',
      'admin.organization.projects.certificates.activate',
      'admin.organization.projects.certificates.deactivate',
      'admin.organization.projects.certificates.list',
      'admin.organization.projects.create',
      'admin.organization.projects.dataRetention.retrieve',
      'admin.organization.projects.dataRetention.update',
      'admin.organization.projects.groups.create',
      'admin.organization.projects.groups.delete',
      'admin.organization.projects.groups.list',
      'admin.organization.projects.groups.retrieve',
      'admin.organization.projects.groups.roles.create',
      'admin.organization.projects.groups.roles.delete',
      'admin.organization.projects.groups.roles.list',
      'admin.organization.projects.groups.roles.retrieve',
      'admin.organization.projects.hostedToolPermissions.retrieve',
      'admin.organization.projects.hostedToolPermissions.update',
      'admin.organization.projects.list',
      'admin.organization.projects.modelPermissions.delete',
      'admin.organization.projects.modelPermissions.retrieve',
      'admin.organization.projects.modelPermissions.update',
      'admin.organization.projects.rateLimits.listRateLimits',
      'admin.organization.projects.rateLimits.updateRateLimit',
      'admin.organization.projects.retrieve',
      'admin.organization.projects.roles.create',
      'admin.organization.projects.roles.delete',
      'admin.organization.projects.roles.list',
      'admin.organization.projects.roles.retrieve',
      'admin.organization.projects.roles.update',
      'admin.organization.projects.serviceAccounts.apiKeys.create',
      'admin.organization.projects.serviceAccounts.create',
      'admin.organization.projects.serviceAccounts.delete',
      'admin.organization.projects.serviceAccounts.list',
      'admin.organization.projects.serviceAccounts.retrieve',
      'admin.organization.projects.serviceAccounts.update',
      'admin.organization.projects.spendAlerts.create',
      'admin.organization.projects.spendAlerts.delete',
      'admin.organization.projects.spendAlerts.list',
      'admin.organization.projects.spendAlerts.retrieve',
      'admin.organization.projects.spendAlerts.update',
      'admin.organization.projects.spendLimit.delete',
      'admin.organization.projects.spendLimit.retrieve',
      'admin.organization.projects.spendLimit.update',
      'admin.organization.projects.update',
      'admin.organization.projects.users.create',
      'admin.organization.projects.users.delete',
      'admin.organization.projects.users.list',
      'admin.organization.projects.users.retrieve',
      'admin.organization.projects.users.roles.create',
      'admin.organization.projects.users.roles.delete',
      'admin.organization.projects.users.roles.list',
      'admin.organization.projects.users.roles.retrieve',
      'admin.organization.projects.users.update',
      'admin.organization.roles.create',
      'admin.organization.roles.delete',
      'admin.organization.roles.list',
      'admin.organization.roles.retrieve',
      'admin.organization.roles.update',
      'admin.organization.spendAlerts.create',
      'admin.organization.spendAlerts.delete',
      'admin.organization.spendAlerts.list',
      'admin.organization.spendAlerts.retrieve',
      'admin.organization.spendAlerts.update',
      'admin.organization.spendLimit.delete',
      'admin.organization.spendLimit.retrieve',
      'admin.organization.spendLimit.update',
      'admin.organization.usage.audioSpeeches',
      'admin.organization.usage.audioTranscriptions',
      'admin.organization.usage.codeInterpreterSessions',
      'admin.organization.usage.completions',
      'admin.organization.usage.costs',
      'admin.organization.usage.embeddings',
      'admin.organization.usage.fileSearchCalls',
      'admin.organization.usage.images',
      'admin.organization.usage.moderations',
      'admin.organization.usage.vectorStores',
      'admin.organization.usage.webSearchCalls',
      'admin.organization.users.delete',
      'admin.organization.users.list',
      'admin.organization.users.retrieve',
      'admin.organization.users.roles.create',
      'admin.organization.users.roles.delete',
      'admin.organization.users.roles.list',
      'admin.organization.users.roles.retrieve',
      'admin.organization.users.update',
      'audio.speech.create',
      'audio.transcriptions.create',
      'audio.translations.create',
      'batches.cancel',
      'batches.create',
      'batches.list',
      'batches.retrieve',
      'beta.assistants.create',
      'beta.assistants.delete',
      'beta.assistants.list',
      'beta.assistants.retrieve',
      'beta.assistants.update',
      'beta.chatkit.sessions.cancel',
      'beta.chatkit.sessions.create',
      'beta.chatkit.threads.delete',
      'beta.chatkit.threads.list',
      'beta.chatkit.threads.listItems',
      'beta.chatkit.threads.retrieve',
      'beta.realtime.sessions.create',
      'beta.realtime.transcriptionSessions.create',
      'beta.responses.cancel',
      'beta.responses.compact',
      'beta.responses.create',
      'beta.responses.delete',
      'beta.responses.inputItems.list',
      'beta.responses.inputTokens.count',
      'beta.responses.retrieve',
      'beta.threads.create',
      'beta.threads.createAndRun',
      'beta.threads.createAndRunPoll',
      'beta.threads.createAndRunStream',
      'beta.threads.delete',
      'beta.threads.messages.create',
      'beta.threads.messages.delete',
      'beta.threads.messages.list',
      'beta.threads.messages.retrieve',
      'beta.threads.messages.update',
      'beta.threads.retrieve',
      'beta.threads.runs.cancel',
      'beta.threads.runs.create',
      'beta.threads.runs.createAndPoll',
      'beta.threads.runs.createAndStream',
      'beta.threads.runs.list',
      'beta.threads.runs.poll',
      'beta.threads.runs.retrieve',
      'beta.threads.runs.steps.list',
      'beta.threads.runs.steps.retrieve',
      'beta.threads.runs.stream',
      'beta.threads.runs.submitToolOutputs',
      'beta.threads.runs.submitToolOutputsAndPoll',
      'beta.threads.runs.submitToolOutputsStream',
      'beta.threads.runs.update',
      'beta.threads.update',
      'chat.completions.create',
      'chat.completions.delete',
      'chat.completions.list',
      'chat.completions.messages.list',
      'chat.completions.parse',
      'chat.completions.retrieve',
      'chat.completions.runTools',
      'chat.completions.stream',
      'chat.completions.update',
      'completions.create',
      'containers.create',
      'containers.delete',
      'containers.files.content.retrieve',
      'containers.files.create',
      'containers.files.delete',
      'containers.files.list',
      'containers.files.retrieve',
      'containers.list',
      'containers.retrieve',
      'contentProvenanceChecks.create',
      'conversations.create',
      'conversations.delete',
      'conversations.items.create',
      'conversations.items.delete',
      'conversations.items.list',
      'conversations.items.retrieve',
      'conversations.retrieve',
      'conversations.update',
      'embeddings.create',
      'evals.create',
      'evals.delete',
      'evals.list',
      'evals.retrieve',
      'evals.runs.cancel',
      'evals.runs.create',
      'evals.runs.delete',
      'evals.runs.list',
      'evals.runs.outputItems.list',
      'evals.runs.outputItems.retrieve',
      'evals.runs.retrieve',
      'evals.update',
      'files.content',
      'files.create',
      'files.delete',
      'files.list',
      'files.retrieve',
      'files.waitForProcessing',
      'fineTuning.alpha.graders.run',
      'fineTuning.alpha.graders.validate',
      'fineTuning.checkpoints.permissions.create',
      'fineTuning.checkpoints.permissions.delete',
      'fineTuning.checkpoints.permissions.list',
      'fineTuning.checkpoints.permissions.retrieve',
      'fineTuning.jobs.cancel',
      'fineTuning.jobs.checkpoints.list',
      'fineTuning.jobs.create',
      'fineTuning.jobs.list',
      'fineTuning.jobs.listEvents',
      'fineTuning.jobs.pause',
      'fineTuning.jobs.resume',
      'fineTuning.jobs.retrieve',
      'images.createVariation',
      'images.edit',
      'images.generate',
      'models.delete',
      'models.list',
      'models.retrieve',
      'moderations.create',
      'realtime.calls.accept',
      'realtime.calls.hangup',
      'realtime.calls.refer',
      'realtime.calls.reject',
      'realtime.clientSecrets.create',
      'responses.cancel',
      'responses.compact',
      'responses.create',
      'responses.delete',
      'responses.inputItems.list',
      'responses.inputTokens.count',
      'responses.parse',
      'responses.retrieve',
      'responses.stream',
      'skills.content.retrieve',
      'skills.create',
      'skills.delete',
      'skills.list',
      'skills.retrieve',
      'skills.update',
      'skills.versions.content.retrieve',
      'skills.versions.create',
      'skills.versions.delete',
      'skills.versions.list',
      'skills.versions.retrieve',
      'uploads.cancel',
      'uploads.complete',
      'uploads.create',
      'uploads.parts.create',
      'vectorStores.create',
      'vectorStores.delete',
      'vectorStores.fileBatches.cancel',
      'vectorStores.fileBatches.create',
      'vectorStores.fileBatches.createAndPoll',
      'vectorStores.fileBatches.listFiles',
      'vectorStores.fileBatches.poll',
      'vectorStores.fileBatches.retrieve',
      'vectorStores.fileBatches.uploadAndPoll',
      'vectorStores.files.content',
      'vectorStores.files.create',
      'vectorStores.files.createAndPoll',
      'vectorStores.files.delete',
      'vectorStores.files.list',
      'vectorStores.files.poll',
      'vectorStores.files.retrieve',
      'vectorStores.files.update',
      'vectorStores.files.upload',
      'vectorStores.files.uploadAndPoll',
      'vectorStores.list',
      'vectorStores.retrieve',
      'vectorStores.search',
      'vectorStores.update',
      'videos.create',
      'videos.createCharacter',
      'videos.delete',
      'videos.downloadContent',
      'videos.edit',
      'videos.extend',
      'videos.getCharacter',
      'videos.list',
      'videos.remix',
      'videos.retrieve',
      'webhooks.unwrap',
      'webhooks.verifySignature',
    ],
  },
  rules: [
    // RULE-DISABLED 2026-07-28 (pre-launch): overfitting, 295/307 (96%) false
    // positives in review. Commenting out the entry disables the rule; rule,
    // tests and fixtures are intact.
    // {
    //   key: 'openai-no-domain-allowlist',
    //   resultRule: 'openai/security/no-domain-allowlist',
    //   message: 'Computer-use actions execute against the current page with no domain/origin allowlist check.',
    //   fix: 'Check the page origin against a configured allowlist before executing click/type/fill actions, and require explicit opt-in for cross-domain navigation.',
    //   docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
    //   severity: 'error',
    // },
    {
      key: 'openai-scroll-delta-default-zero',
      resultRule: 'openai/correctness/scroll-delta-default-zero',
      message: 'A missing vertical scroll delta defaults to a non-zero value instead of 0.',
      fix: 'Default the missing scroll delta to 0 on both axes, matching the reference scroll handler.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
      severity: 'error',
    },
    {
      key: 'openai-structured-step-metadata-not-text-json',
      resultRule: 'openai/correctness/structured-step-metadata-not-text-json',
      message: 'Step metadata is extracted by brace-hunting in free text instead of structured tool output.',
      fix: 'Add a function tool (e.g. report_step) or use structured output (text.format) instead of parsing JSON found via indexOf/lastIndexOf in the message text.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
      severity: 'warning',
    },
    {
      key: 'openai-no-blind-safety-check-ack',
      resultRule: 'openai/correctness/no-blind-safety-check-ack',
      message: 'Pending safety checks are acknowledged by a filter that never inspects .code or .message.',
      fix: 'Evaluate each check\'s code/message against an actual policy before acknowledging it, or omit acknowledged_safety_checks entirely if you rely on harness-level confirmation instead.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
      severity: 'warning',
    },
    {
      key: 'openai-retry-transient-turn-errors',
      resultRule: 'openai/reliability/retry-transient-turn-errors',
      message: 'responses.create() has no turn-level retry, so a transient error ends the entire run.',
      fix: 'Catch typed transient exceptions (RateLimitError, APIConnectionError, InternalServerError) and retry that turn with backoff before falling back to ending the run.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
      severity: 'error',
    },
    {
      key: 'openai-check-response-status-incomplete',
      resultRule: 'openai/reliability/check-response-status-incomplete',
      message: 'A completion check treats "no tool calls" as success without checking response.status === "incomplete".',
      fix: 'Check response.status === "incomplete" before treating a tool-call-free response as a successful completion; retry with a larger token budget or fail the run explicitly otherwise.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/tools-computer-use',
      severity: 'error',
    },
    {
      key: 'openai-set-safety-identifier',
      resultRule: 'openai/correctness/set-safety-identifier',
      message: 'responses.create() call has no safety_identifier (or user) parameter.',
      fix: 'Thread a stable, hashed per-customer identifier through to every responses.create() call as safety_identifier.',
      docsUrl: 'https://developers.openai.com/api/docs/guides/safety-best-practices',
      severity: 'warning',
    },
  ],
};
