import type { ProviderManifest } from '../../types.js';

export const twilioManifest: ProviderManifest = {
  name: 'twilio',
  displayName: 'Twilio',
  detect: {
    packages: ['twilio'],
    imports: ['twilio'],
    urlPatterns: ['api.twilio.com'],
  },
  oxlintRules: [
    {
      key: 'twilio-validate-webhook-signature',
      resultRule: 'twilio/security/validate-webhook-signature',
      message: 'A POST webhook route reads req.body but never validates the X-Twilio-Signature header.',
      fix: 'Validate the X-Twilio-Signature header with twilio.validateRequest()/RequestValidator before trusting the body.',
      docsUrl: 'https://www.twilio.com/docs/usage/webhooks/webhooks-security',
      severity: 'error',
    },
    {
      key: 'twilio-taskrouter-attributes-match-consumer',
      resultRule: 'twilio/correctness/taskrouter-attributes-match-consumer',
      message: 'A .task() attributes object is missing a field that a reservation handler reads back out of TaskAttributes.',
      fix: 'Add the missing field to the Task attributes object so the consumer\'s JSON.parse(TaskAttributes) destructure actually finds it.',
      docsUrl: 'https://www.twilio.com/docs/taskrouter/twiml-queue-calls',
      severity: 'error',
    },
    {
      key: 'twilio-enqueue-task-json-stringify',
      resultRule: 'twilio/security/enqueue-task-json-stringify',
      message: 'A .task() call builds JSON attributes via raw string interpolation instead of JSON.stringify().',
      fix: 'Build the Task attributes as an object and serialize with JSON.stringify() instead of interpolating values into a JSON string/template literal.',
      docsUrl: 'https://www.twilio.com/docs/api/errors/14221',
      severity: 'error',
    },
    {
      key: 'twilio-media-streams-key-by-call-sid',
      resultRule: 'twilio/reliability/media-streams-key-by-call-sid',
      message: 'A Media Streams session map is keyed by a phone-number-like field instead of callSid.',
      fix: 'Key the map by start.callSid instead of the caller phone number, and propagate callSid (not the number) downstream as the lookup key.',
      docsUrl: 'https://www.twilio.com/docs/voice/media-streams/websocket-messages',
      severity: 'error',
    },
    {
      key: 'twilio-await-or-catch-rest-calls-in-event-handlers',
      resultRule: 'twilio/reliability/await-or-catch-rest-calls-in-event-handlers',
      message: 'A Twilio REST call inside an event-handler callback has no surrounding try/catch.',
      fix: 'Wrap the REST call in try/catch inside the handler so a rejected promise does not become an unhandled rejection.',
      docsUrl: 'https://www.twilio.com/docs/usage/webhooks/webhooks-faq',
      severity: 'error',
    },
    {
      key: 'twilio-use-twiml-builder-not-string-templates',
      resultRule: 'twilio/security/use-twiml-builder-not-string-templates',
      message: 'TwiML is built as a raw template literal instead of the VoiceResponse builder.',
      fix: 'Build TwiML with new VoiceResponse() and its builder methods (say, connect, stream, parameter) instead of interpolating values into an XML template literal.',
      docsUrl: 'https://www.twilio.com/docs/voice/twiml/stream',
      severity: 'warning',
    },
    {
      key: 'twilio-media-streams-mark-pacing',
      resultRule: 'twilio/reliability/media-streams-mark-pacing',
      message: 'Media is forwarded to a Stream with no mark-based pacing (isLast) anywhere in the file.',
      fix: 'Pace sends with mark events (pass isLast: true periodically) and wait for the inbound mark acknowledgment before queuing more audio.',
      docsUrl: 'https://www.twilio.com/docs/api/errors/31931',
      severity: 'warning',
    },
    {
      key: 'twilio-validate-all-request-inputs',
      resultRule: 'twilio/correctness/validate-all-request-inputs',
      message: 'A webhook route reads a request field that is not covered by its schema (or has no schema at all).',
      fix: 'Add a querystring/body schema covering every field the handler reads, and reject the request with a 400 if a required field is missing.',
      docsUrl: 'https://www.twilio.com/docs/voice/twiml/stream',
      severity: 'warning',
    },
    {
      key: 'twilio-media-streams-mark-name-string',
      resultRule: 'twilio/correctness/media-streams-mark-name-string',
      message: 'mark.name is set to a non-string value (Twilio requires a string).',
      fix: 'Wrap the value in String(...) (e.g. String(Date.now())) so mark.name matches Twilio\'s documented string schema.',
      docsUrl: 'https://www.twilio.com/docs/voice/media-streams/websocket-messages',
      severity: 'warning',
    },
  ],
};
