import type { ProviderManifest } from '../../types.js';

export const twilioManifest: ProviderManifest = {
  name: 'twilio',
  displayName: 'Twilio',
  detect: {
    packages: ['twilio'],
    imports: ['twilio'],
    urlPatterns: ['api.twilio.com'],
  },
  surface: {
    packages: ['twilio'],
    // 'Twilio' is the exported client class (import { Twilio } from 'twilio').
    // 'twilio' covers the documented default-export factory pattern
    // (import twilio from 'twilio'; const client = twilio(sid, token)) — the
    // default export is itself the client factory (lib/index.d.ts:
    // declare function TwilioSDK(...): TwilioSDK.Twilio), so a default import
    // bound to the conventional name is treated as a constructor local, which
    // lets the collector verify factory-call constructions.
    clientConstructors: ['Twilio', 'twilio'],
    clientNamePattern: /^twilio([-_]?(client|rest))?$/i,
    docsUrl: 'https://www.twilio.com/docs/usage/api',
    // SCOPE — twilio-node spans ~40 API domains with 1000+ operations; this
    // surface deliberately covers the client's documented api.v2010 shortcut
    // accessors (client.messages, client.calls, … — the 24 root getters on
    // lib/rest/Twilio.d.ts plus the one under client.taskrouter, the REST
    // domain this provider's rules lint). Out of surface scope, by decision
    // 2026-07-29: every other domain root (accounts, api (long-form
    // api.v2010.* paths), assistants, bulkexports, chat, content,
    // conversations, events, flexApi, frontlineApi, iam, insights,
    // intelligence, ipMessaging, knowledge, lookups, marketplace, memory,
    // messaging, monitor, notify, numbers, oauth, preview, previewIam,
    // pricing, proxy, routes, serverless, studio, supersim, sync, trunking,
    // trusthub, verify, video, voice, wireless) — calls on them land in
    // unknown_sdk_calls, by design.
    // PATH SHAPES — twilio-node reaches instance resources through callable
    // list accessors: client.calls('CA…').update() is a call through an
    // intermediate call expression, which the coverage collector attributes
    // only up to the inner call — recorded as the accessor's own path
    // ('calls'). Bare entries below ('messages', 'calls',
    // 'taskrouter.v1.workspaces', …) are exactly those callable context
    // accessors; everything past a sid call (instance fetch/update/remove and
    // sid-scoped subresources like calls('CA').recordings) is unattributable
    // and collapses into the accessor path. Non-callable accessors (balance,
    // sip, tokens, newKeys, newSigningKeys, validationRequests, usage.records)
    // deliberately have no bare entry.
    // Verified against twilio@6.0.2 lib/rest/Twilio.d.ts (root getters walked
    // into domain classes, their *Base parents, and callable ListInstance
    // interfaces) and cross-checked against twilio-oai spec/yaml
    // twilio_api_v2010.yaml + twilio_taskrouter_v1.yaml: all 193
    // account-level v2010 endpoints and the 5 /v1/Workspaces root endpoints
    // map onto entries below (56 deeper taskrouter endpoints sit behind the
    // workspace sid call). SDK-side extras, each justified: *WithHttpInfo
    // (typed response-info variants of the same endpoints), each/page/getPage
    // (pagination helpers over the same list GET), <resource>.get (documented
    // alias of the callable accessor), taskrouter.workspaces.* (domain-level
    // shortcut alias of taskrouter.v1.workspaces.*), and the create quirks
    // newKeys/newSigningKeys/validationRequests (SDK names for POST /Keys,
    // POST /SigningKeys, POST /OutgoingCallerIds). toJSON is excluded as a
    // serialization helper. Low-level transport (client.request, httpClient)
    // is deliberately absent — those calls must surface in unknown_sdk_calls.
    methods: [
      'addresses',
      'addresses.create',
      'addresses.createWithHttpInfo',
      'addresses.each',
      'addresses.eachWithHttpInfo',
      'addresses.get',
      'addresses.getPage',
      'addresses.getPageWithHttpInfo',
      'addresses.list',
      'addresses.listWithHttpInfo',
      'addresses.page',
      'addresses.pageWithHttpInfo',
      'applications',
      'applications.create',
      'applications.createWithHttpInfo',
      'applications.each',
      'applications.eachWithHttpInfo',
      'applications.get',
      'applications.getPage',
      'applications.getPageWithHttpInfo',
      'applications.list',
      'applications.listWithHttpInfo',
      'applications.page',
      'applications.pageWithHttpInfo',
      'authorizedConnectApps',
      'authorizedConnectApps.each',
      'authorizedConnectApps.eachWithHttpInfo',
      'authorizedConnectApps.get',
      'authorizedConnectApps.getPage',
      'authorizedConnectApps.getPageWithHttpInfo',
      'authorizedConnectApps.list',
      'authorizedConnectApps.listWithHttpInfo',
      'authorizedConnectApps.page',
      'authorizedConnectApps.pageWithHttpInfo',
      'availablePhoneNumbers',
      'availablePhoneNumbers.each',
      'availablePhoneNumbers.eachWithHttpInfo',
      'availablePhoneNumbers.get',
      'availablePhoneNumbers.getPage',
      'availablePhoneNumbers.getPageWithHttpInfo',
      'availablePhoneNumbers.list',
      'availablePhoneNumbers.listWithHttpInfo',
      'availablePhoneNumbers.page',
      'availablePhoneNumbers.pageWithHttpInfo',
      'balance.fetch',
      'balance.fetchWithHttpInfo',
      'calls',
      'calls.create',
      'calls.createWithHttpInfo',
      'calls.each',
      'calls.eachWithHttpInfo',
      'calls.get',
      'calls.getPage',
      'calls.getPageWithHttpInfo',
      'calls.list',
      'calls.listWithHttpInfo',
      'calls.page',
      'calls.pageWithHttpInfo',
      'conferences',
      'conferences.each',
      'conferences.eachWithHttpInfo',
      'conferences.get',
      'conferences.getPage',
      'conferences.getPageWithHttpInfo',
      'conferences.list',
      'conferences.listWithHttpInfo',
      'conferences.page',
      'conferences.pageWithHttpInfo',
      'connectApps',
      'connectApps.each',
      'connectApps.eachWithHttpInfo',
      'connectApps.get',
      'connectApps.getPage',
      'connectApps.getPageWithHttpInfo',
      'connectApps.list',
      'connectApps.listWithHttpInfo',
      'connectApps.page',
      'connectApps.pageWithHttpInfo',
      'incomingPhoneNumbers',
      'incomingPhoneNumbers.create',
      'incomingPhoneNumbers.createWithHttpInfo',
      'incomingPhoneNumbers.each',
      'incomingPhoneNumbers.eachWithHttpInfo',
      'incomingPhoneNumbers.get',
      'incomingPhoneNumbers.getPage',
      'incomingPhoneNumbers.getPageWithHttpInfo',
      'incomingPhoneNumbers.list',
      'incomingPhoneNumbers.listWithHttpInfo',
      'incomingPhoneNumbers.local.create',
      'incomingPhoneNumbers.local.createWithHttpInfo',
      'incomingPhoneNumbers.local.each',
      'incomingPhoneNumbers.local.eachWithHttpInfo',
      'incomingPhoneNumbers.local.getPage',
      'incomingPhoneNumbers.local.getPageWithHttpInfo',
      'incomingPhoneNumbers.local.list',
      'incomingPhoneNumbers.local.listWithHttpInfo',
      'incomingPhoneNumbers.local.page',
      'incomingPhoneNumbers.local.pageWithHttpInfo',
      'incomingPhoneNumbers.mobile.create',
      'incomingPhoneNumbers.mobile.createWithHttpInfo',
      'incomingPhoneNumbers.mobile.each',
      'incomingPhoneNumbers.mobile.eachWithHttpInfo',
      'incomingPhoneNumbers.mobile.getPage',
      'incomingPhoneNumbers.mobile.getPageWithHttpInfo',
      'incomingPhoneNumbers.mobile.list',
      'incomingPhoneNumbers.mobile.listWithHttpInfo',
      'incomingPhoneNumbers.mobile.page',
      'incomingPhoneNumbers.mobile.pageWithHttpInfo',
      'incomingPhoneNumbers.page',
      'incomingPhoneNumbers.pageWithHttpInfo',
      'incomingPhoneNumbers.tollFree.create',
      'incomingPhoneNumbers.tollFree.createWithHttpInfo',
      'incomingPhoneNumbers.tollFree.each',
      'incomingPhoneNumbers.tollFree.eachWithHttpInfo',
      'incomingPhoneNumbers.tollFree.getPage',
      'incomingPhoneNumbers.tollFree.getPageWithHttpInfo',
      'incomingPhoneNumbers.tollFree.list',
      'incomingPhoneNumbers.tollFree.listWithHttpInfo',
      'incomingPhoneNumbers.tollFree.page',
      'incomingPhoneNumbers.tollFree.pageWithHttpInfo',
      'keys',
      'keys.each',
      'keys.eachWithHttpInfo',
      'keys.get',
      'keys.getPage',
      'keys.getPageWithHttpInfo',
      'keys.list',
      'keys.listWithHttpInfo',
      'keys.page',
      'keys.pageWithHttpInfo',
      'messages',
      'messages.create',
      'messages.createWithHttpInfo',
      'messages.each',
      'messages.eachWithHttpInfo',
      'messages.get',
      'messages.getPage',
      'messages.getPageWithHttpInfo',
      'messages.list',
      'messages.listWithHttpInfo',
      'messages.page',
      'messages.pageWithHttpInfo',
      'newKeys.create',
      'newKeys.createWithHttpInfo',
      'newSigningKeys.create',
      'newSigningKeys.createWithHttpInfo',
      'notifications',
      'notifications.each',
      'notifications.eachWithHttpInfo',
      'notifications.get',
      'notifications.getPage',
      'notifications.getPageWithHttpInfo',
      'notifications.list',
      'notifications.listWithHttpInfo',
      'notifications.page',
      'notifications.pageWithHttpInfo',
      'outgoingCallerIds',
      'outgoingCallerIds.each',
      'outgoingCallerIds.eachWithHttpInfo',
      'outgoingCallerIds.get',
      'outgoingCallerIds.getPage',
      'outgoingCallerIds.getPageWithHttpInfo',
      'outgoingCallerIds.list',
      'outgoingCallerIds.listWithHttpInfo',
      'outgoingCallerIds.page',
      'outgoingCallerIds.pageWithHttpInfo',
      'queues',
      'queues.create',
      'queues.createWithHttpInfo',
      'queues.each',
      'queues.eachWithHttpInfo',
      'queues.get',
      'queues.getPage',
      'queues.getPageWithHttpInfo',
      'queues.list',
      'queues.listWithHttpInfo',
      'queues.page',
      'queues.pageWithHttpInfo',
      'recordings',
      'recordings.each',
      'recordings.eachWithHttpInfo',
      'recordings.get',
      'recordings.getPage',
      'recordings.getPageWithHttpInfo',
      'recordings.list',
      'recordings.listWithHttpInfo',
      'recordings.page',
      'recordings.pageWithHttpInfo',
      'shortCodes',
      'shortCodes.each',
      'shortCodes.eachWithHttpInfo',
      'shortCodes.get',
      'shortCodes.getPage',
      'shortCodes.getPageWithHttpInfo',
      'shortCodes.list',
      'shortCodes.listWithHttpInfo',
      'shortCodes.page',
      'shortCodes.pageWithHttpInfo',
      'signingKeys',
      'signingKeys.each',
      'signingKeys.eachWithHttpInfo',
      'signingKeys.get',
      'signingKeys.getPage',
      'signingKeys.getPageWithHttpInfo',
      'signingKeys.list',
      'signingKeys.listWithHttpInfo',
      'signingKeys.page',
      'signingKeys.pageWithHttpInfo',
      'sip.credentialLists',
      'sip.credentialLists.create',
      'sip.credentialLists.createWithHttpInfo',
      'sip.credentialLists.each',
      'sip.credentialLists.eachWithHttpInfo',
      'sip.credentialLists.get',
      'sip.credentialLists.getPage',
      'sip.credentialLists.getPageWithHttpInfo',
      'sip.credentialLists.list',
      'sip.credentialLists.listWithHttpInfo',
      'sip.credentialLists.page',
      'sip.credentialLists.pageWithHttpInfo',
      'sip.domains',
      'sip.domains.create',
      'sip.domains.createWithHttpInfo',
      'sip.domains.each',
      'sip.domains.eachWithHttpInfo',
      'sip.domains.get',
      'sip.domains.getPage',
      'sip.domains.getPageWithHttpInfo',
      'sip.domains.list',
      'sip.domains.listWithHttpInfo',
      'sip.domains.page',
      'sip.domains.pageWithHttpInfo',
      'sip.ipAccessControlLists',
      'sip.ipAccessControlLists.create',
      'sip.ipAccessControlLists.createWithHttpInfo',
      'sip.ipAccessControlLists.each',
      'sip.ipAccessControlLists.eachWithHttpInfo',
      'sip.ipAccessControlLists.get',
      'sip.ipAccessControlLists.getPage',
      'sip.ipAccessControlLists.getPageWithHttpInfo',
      'sip.ipAccessControlLists.list',
      'sip.ipAccessControlLists.listWithHttpInfo',
      'sip.ipAccessControlLists.page',
      'sip.ipAccessControlLists.pageWithHttpInfo',
      'taskrouter.v1.workspaces',
      'taskrouter.v1.workspaces.create',
      'taskrouter.v1.workspaces.createWithHttpInfo',
      'taskrouter.v1.workspaces.each',
      'taskrouter.v1.workspaces.eachWithHttpInfo',
      'taskrouter.v1.workspaces.get',
      'taskrouter.v1.workspaces.getPage',
      'taskrouter.v1.workspaces.getPageWithHttpInfo',
      'taskrouter.v1.workspaces.list',
      'taskrouter.v1.workspaces.listWithHttpInfo',
      'taskrouter.v1.workspaces.page',
      'taskrouter.v1.workspaces.pageWithHttpInfo',
      'taskrouter.workspaces',
      'taskrouter.workspaces.create',
      'taskrouter.workspaces.createWithHttpInfo',
      'taskrouter.workspaces.each',
      'taskrouter.workspaces.eachWithHttpInfo',
      'taskrouter.workspaces.get',
      'taskrouter.workspaces.getPage',
      'taskrouter.workspaces.getPageWithHttpInfo',
      'taskrouter.workspaces.list',
      'taskrouter.workspaces.listWithHttpInfo',
      'taskrouter.workspaces.page',
      'taskrouter.workspaces.pageWithHttpInfo',
      'tokens.create',
      'tokens.createWithHttpInfo',
      'transcriptions',
      'transcriptions.each',
      'transcriptions.eachWithHttpInfo',
      'transcriptions.get',
      'transcriptions.getPage',
      'transcriptions.getPageWithHttpInfo',
      'transcriptions.list',
      'transcriptions.listWithHttpInfo',
      'transcriptions.page',
      'transcriptions.pageWithHttpInfo',
      'usage.records.allTime.each',
      'usage.records.allTime.eachWithHttpInfo',
      'usage.records.allTime.getPage',
      'usage.records.allTime.getPageWithHttpInfo',
      'usage.records.allTime.list',
      'usage.records.allTime.listWithHttpInfo',
      'usage.records.allTime.page',
      'usage.records.allTime.pageWithHttpInfo',
      'usage.records.daily.each',
      'usage.records.daily.eachWithHttpInfo',
      'usage.records.daily.getPage',
      'usage.records.daily.getPageWithHttpInfo',
      'usage.records.daily.list',
      'usage.records.daily.listWithHttpInfo',
      'usage.records.daily.page',
      'usage.records.daily.pageWithHttpInfo',
      'usage.records.each',
      'usage.records.eachWithHttpInfo',
      'usage.records.getPage',
      'usage.records.getPageWithHttpInfo',
      'usage.records.lastMonth.each',
      'usage.records.lastMonth.eachWithHttpInfo',
      'usage.records.lastMonth.getPage',
      'usage.records.lastMonth.getPageWithHttpInfo',
      'usage.records.lastMonth.list',
      'usage.records.lastMonth.listWithHttpInfo',
      'usage.records.lastMonth.page',
      'usage.records.lastMonth.pageWithHttpInfo',
      'usage.records.list',
      'usage.records.listWithHttpInfo',
      'usage.records.monthly.each',
      'usage.records.monthly.eachWithHttpInfo',
      'usage.records.monthly.getPage',
      'usage.records.monthly.getPageWithHttpInfo',
      'usage.records.monthly.list',
      'usage.records.monthly.listWithHttpInfo',
      'usage.records.monthly.page',
      'usage.records.monthly.pageWithHttpInfo',
      'usage.records.page',
      'usage.records.pageWithHttpInfo',
      'usage.records.thisMonth.each',
      'usage.records.thisMonth.eachWithHttpInfo',
      'usage.records.thisMonth.getPage',
      'usage.records.thisMonth.getPageWithHttpInfo',
      'usage.records.thisMonth.list',
      'usage.records.thisMonth.listWithHttpInfo',
      'usage.records.thisMonth.page',
      'usage.records.thisMonth.pageWithHttpInfo',
      'usage.records.today.each',
      'usage.records.today.eachWithHttpInfo',
      'usage.records.today.getPage',
      'usage.records.today.getPageWithHttpInfo',
      'usage.records.today.list',
      'usage.records.today.listWithHttpInfo',
      'usage.records.today.page',
      'usage.records.today.pageWithHttpInfo',
      'usage.records.yearly.each',
      'usage.records.yearly.eachWithHttpInfo',
      'usage.records.yearly.getPage',
      'usage.records.yearly.getPageWithHttpInfo',
      'usage.records.yearly.list',
      'usage.records.yearly.listWithHttpInfo',
      'usage.records.yearly.page',
      'usage.records.yearly.pageWithHttpInfo',
      'usage.records.yesterday.each',
      'usage.records.yesterday.eachWithHttpInfo',
      'usage.records.yesterday.getPage',
      'usage.records.yesterday.getPageWithHttpInfo',
      'usage.records.yesterday.list',
      'usage.records.yesterday.listWithHttpInfo',
      'usage.records.yesterday.page',
      'usage.records.yesterday.pageWithHttpInfo',
      'usage.triggers',
      'usage.triggers.create',
      'usage.triggers.createWithHttpInfo',
      'usage.triggers.each',
      'usage.triggers.eachWithHttpInfo',
      'usage.triggers.get',
      'usage.triggers.getPage',
      'usage.triggers.getPageWithHttpInfo',
      'usage.triggers.list',
      'usage.triggers.listWithHttpInfo',
      'usage.triggers.page',
      'usage.triggers.pageWithHttpInfo',
      'validationRequests.create',
      'validationRequests.createWithHttpInfo',
    ],
  },
  rules: [
    // RULE-DISABLED 2026-07-28 (pre-launch): overfitting, 662/706 (94%) false
    // positives in review. The rule, its tests and its fixtures are all intact —
    // only this manifest entry is commented out, so nothing enables it for a
    // scan. Re-enable by uncommenting once the heuristic is tightened.
    // {
    //   key: 'twilio-validate-webhook-signature',
    //   resultRule: 'twilio/security/validate-webhook-signature',
    //   message: 'A POST webhook route reads req.body but never validates the X-Twilio-Signature header.',
    //   fix: 'Validate the X-Twilio-Signature header with twilio.validateRequest()/RequestValidator before trusting the body.',
    //   docsUrl: 'https://www.twilio.com/docs/usage/webhooks/webhooks-security',
    //   severity: 'error',
    // },
    {
      key: 'twilio-taskrouter-attributes-match-consumer',
      resultRule: 'twilio/correctness/taskrouter-attributes-match-consumer',
      message: 'A .task() attributes object is missing a field that a reservation handler reads back out of TaskAttributes.',
      fix: 'Add the missing field to the Task attributes object so the consumer\'s JSON.parse(TaskAttributes) destructure actually finds it.',
      docsUrl: 'https://www.twilio.com/docs/taskrouter/twiml-queue-calls',
      severity: 'error',
    },
    {
      key: 'twilio-enqueue-task-json-stringify',
      resultRule: 'twilio/security/enqueue-task-json-stringify',
      message: 'A .task() call builds JSON attributes via raw string interpolation instead of JSON.stringify().',
      fix: 'Build the Task attributes as an object and serialize with JSON.stringify() instead of interpolating values into a JSON string/template literal.',
      docsUrl: 'https://www.twilio.com/docs/api/errors/14221',
      severity: 'error',
    },
    {
      key: 'twilio-media-streams-key-by-call-sid',
      resultRule: 'twilio/reliability/media-streams-key-by-call-sid',
      message: 'A Media Streams session map is keyed by a phone-number-like field instead of callSid.',
      fix: 'Key the map by start.callSid instead of the caller phone number, and propagate callSid (not the number) downstream as the lookup key.',
      docsUrl: 'https://www.twilio.com/docs/voice/media-streams/websocket-messages',
      severity: 'error',
    },
    {
      key: 'twilio-await-or-catch-rest-calls-in-event-handlers',
      resultRule: 'twilio/reliability/await-or-catch-rest-calls-in-event-handlers',
      message: 'A Twilio REST call inside an event-handler callback has no surrounding try/catch.',
      fix: 'Wrap the REST call in try/catch inside the handler so a rejected promise does not become an unhandled rejection.',
      docsUrl: 'https://www.twilio.com/docs/usage/webhooks/webhooks-faq',
      severity: 'error',
    },
    {
      key: 'twilio-use-twiml-builder-not-string-templates',
      resultRule: 'twilio/security/use-twiml-builder-not-string-templates',
      message: 'TwiML is built as a raw template literal instead of the VoiceResponse builder.',
      fix: 'Build TwiML with new VoiceResponse() and its builder methods (say, connect, stream, parameter) instead of interpolating values into an XML template literal.',
      docsUrl: 'https://www.twilio.com/docs/voice/twiml/stream',
      severity: 'warning',
    },
    {
      key: 'twilio-media-streams-mark-pacing',
      resultRule: 'twilio/reliability/media-streams-mark-pacing',
      message: 'Media is forwarded to a Stream with no mark-based pacing (isLast) anywhere in the file.',
      fix: 'Pace sends with mark events (pass isLast: true periodically) and wait for the inbound mark acknowledgment before queuing more audio.',
      docsUrl: 'https://www.twilio.com/docs/api/errors/31931',
      severity: 'warning',
    },
    // RULE-DISABLED 2026-07-28 (pre-launch): overfitting, 81/89 (91%) false
    // positives in review. Rule, tests and fixtures intact — see the note on
    // twilio-validate-webhook-signature above.
    // {
    //   key: 'twilio-validate-all-request-inputs',
    //   resultRule: 'twilio/correctness/validate-all-request-inputs',
    //   message: 'A webhook route reads a request field that is not covered by its schema (or has no schema at all).',
    //   fix: 'Add a querystring/body schema covering every field the handler reads, and reject the request with a 400 if a required field is missing.',
    //   docsUrl: 'https://www.twilio.com/docs/voice/twiml/stream',
    //   severity: 'warning',
    // },
    {
      key: 'twilio-media-streams-mark-name-string',
      resultRule: 'twilio/correctness/media-streams-mark-name-string',
      message: 'mark.name is set to a non-string value (Twilio requires a string).',
      fix: 'Wrap the value in String(...) (e.g. String(Date.now())) so mark.name matches Twilio\'s documented string schema.',
      docsUrl: 'https://www.twilio.com/docs/voice/media-streams/websocket-messages',
      severity: 'warning',
    },
  ],
};
