import type { ProviderManifest } from '../../types.js';

export const browserbaseManifest: ProviderManifest = {
  name: 'browserbase',
  displayName: 'Browserbase',
  detect: {
    packages: ['@browserbasehq/sdk'],
    imports: ['@browserbasehq/sdk'],
    urlPatterns: ['api.browserbase.com'],
  },
  oxlintRules: [
    {
      key: 'browserbase-no-conditional-authz-on-anonymous-user',
      resultRule: 'browserbase/security/no-conditional-authz-on-anonymous-user',
      message: 'A Browserbase live-view/recording resource is gated only by a conditional authz check.',
      fix: 'Add an unconditional `if (!user) return ...` guard before the ownership check, so anonymous callers are rejected, not skipped past.',
      docsUrl: 'https://docs.browserbase.com/reference/api/session-live-urls',
      severity: 'error',
    },
    {
      key: 'browserbase-no-connect-url-in-api-response',
      resultRule: 'browserbase/security/no-connect-url-in-api-response',
      message: 'connectUrl (a bearer credential for the live browser) is included in an HTTP response.',
      fix: 'Omit connectUrl from the response body — keep it server-side only. Share debuggerFullscreenUrl from sessions.debug() instead.',
      docsUrl: 'https://docs.browserbase.com/reference/api/create-a-session',
      severity: 'error',
    },
    {
      key: 'browserbase-session-id-requires-ownership-check',
      resultRule: 'browserbase/security/session-id-requires-ownership-check',
      message: 'sessionId flows into a live-view/recording call with no ownership check.',
      fix: 'Look up the owning project/org by sessionId and verify the requesting user has access before calling sessions.debug()/recording.retrieve().',
      docsUrl: 'https://docs.browserbase.com/features/session-live-view',
      severity: 'warning',
    },
    {
      key: 'browserbase-no-concurrent-shared-context',
      resultRule: 'browserbase/correctness/no-concurrent-shared-context',
      message: 'The same Context id is passed into every session in a concurrent Promise.all batch.',
      fix: 'Serialize sessions that share a context id, or create a fresh Context per concurrent run.',
      docsUrl: 'https://docs.browserbase.com/features/contexts',
      severity: 'error',
    },
    {
      key: 'browserbase-mobile-device-requires-os-setting',
      resultRule: 'browserbase/correctness/mobile-device-requires-os-setting',
      message: 'A "mobile" device branch resizes the viewport but never sets browserSettings.os.',
      fix: "Set browserSettings.os = 'mobile' (or 'tablet') alongside the viewport resize — the Node SDK's device-emulation lever is `os`, not a fingerprint object.",
      docsUrl: 'https://docs.browserbase.com/features/stealth-mode',
      severity: 'error',
    },
    {
      key: 'browserbase-use-typed-exception-status-not-substring',
      resultRule: 'browserbase/correctness/use-typed-exception-status-not-substring',
      message: 'Error handling matches a substring of the stringified error instead of err.status.',
      fix: 'Check err.status (or `instanceof Browserbase.APIError`/`NotFoundError`) instead of matching message text.',
      docsUrl: 'https://docs.browserbase.com/reference/api/session-live-urls',
      severity: 'info',
    },
    {
      key: 'browserbase-release-session-on-connect-failure',
      resultRule: 'browserbase/reliability/release-session-on-connect-failure',
      message: 'A connect call after session creation has no catch that releases the session on failure.',
      fix: 'Wrap the connect call in try/catch and call sessions.update(id, { status: "REQUEST_RELEASE" }) on failure.',
      docsUrl: 'https://docs.browserbase.com/reference/api/update-a-session',
      severity: 'error',
    },
    {
      key: 'browserbase-dont-stack-custom-retry-on-sdk-retry',
      resultRule: 'browserbase/reliability/dont-stack-custom-retry-on-sdk-retry',
      message: 'sessions.create() is called inside a custom retry loop without disabling the SDK\'s own retry.',
      fix: 'Pass { maxRetries: 0 } to sessions.create() so the outer loop is the only thing retrying.',
      docsUrl: 'https://docs.browserbase.com/optimizations/concurrency/overview',
      severity: 'warning',
    },
    {
      key: 'browserbase-no-overbroad-error-substring-match',
      resultRule: 'browserbase/reliability/no-overbroad-error-substring-match',
      message: 'An error-message OR-chain includes an overly broad resource-name substring.',
      fix: 'Match on err.status/`instanceof` instead of a generic word like "session" that matches almost any error from this call.',
      docsUrl: 'https://docs.browserbase.com/reference/api/session-live-urls',
      severity: 'error',
    },
    {
      key: 'browserbase-use-sdk-not-raw-requests',
      resultRule: 'browserbase/integration/use-sdk-not-raw-requests',
      message: 'A raw HTTP request targets a Browserbase API endpoint instead of using the SDK.',
      fix: 'Replace the raw fetch/axios/http call with the equivalent installed-SDK method.',
      docsUrl: 'https://docs.browserbase.com/reference/sdk/nodejs',
      severity: 'info',
    },
    {
      key: 'browserbase-centralize-request-release',
      resultRule: 'browserbase/integration/centralize-request-release',
      message: 'REQUEST_RELEASE is hand-rolled inline instead of going through a shared abstraction.',
      fix: 'Route this call through a single designated release/provider method instead of inlining sessions.update(..., { status: "REQUEST_RELEASE" }).',
      docsUrl: 'https://docs.browserbase.com/reference/api/update-a-session',
      severity: 'warning',
    },
  ],
};
