import type { ProviderManifest } from '../../types.js';

export const firebaseManifest: ProviderManifest = {
  name: 'firebase',
  displayName: 'Firebase',
  detect: {
    packages: ['firebase'],
    imports: ['firebase/app', 'firebase/auth', 'firebase/database', 'firebase/app-check'],
    urlPatterns: ['firebaseio.com', 'firebaseapp.com'],
  },
  oxlintRules: [
    {
      key: 'firebase-missing-app-check',
      resultRule: 'firebase/security/missing-app-check',
      message: 'Firebase app is initialized with no App Check configured.',
      fix: 'Call initializeAppCheck(app, { provider: new ReCaptchaV3Provider(SITE_KEY), isTokenAutoRefreshEnabled: true }) alongside initializeApp.',
      docsUrl: 'https://firebase.google.com/docs/database/web/start',
      severity: 'warning',
    },
    {
      key: 'firebase-unhandled-auth-popup-rejection',
      resultRule: 'firebase/correctness/unhandled-auth-popup-rejection',
      message: 'signInWithPopup is called with no try/catch and no chained .catch.',
      fix: 'Wrap the call in try/catch (and finally, to clear loading state) — popup-closed-by-user and popup-blocked are expected rejections.',
      docsUrl: 'https://firebase.google.com/docs/auth/web/google-signin',
      severity: 'error',
    },
    {
      key: 'firebase-rtdb-list-read-for-single-item',
      resultRule: 'firebase/correctness/rtdb-list-read-for-single-item',
      message: 'A whole collection is subscribed to and then searched for one item by a route id param.',
      fix: 'Read/subscribe to the single node directly, e.g. ref(db, `path/${id}`), instead of finding it in the full list.',
      docsUrl: 'https://firebase.google.com/docs/database/web/read-and-write',
      severity: 'warning',
    },
    {
      key: 'firebase-unvalidated-external-data-to-rtdb',
      resultRule: 'firebase/correctness/unvalidated-external-data-to-rtdb',
      message: 'Parsed external data is written to the Realtime Database with no validation.',
      fix: 'Validate shape/values (e.g. regex-check date fields) before calling set()/update()/push(), and surface a parse-quality warning for skipped items.',
      docsUrl: 'https://firebase.google.com/docs/database/web/read-and-write',
      severity: 'error',
    },
    {
      key: 'firebase-rtdb-batch-write-not-atomic',
      resultRule: 'firebase/correctness/rtdb-batch-write-not-atomic',
      message: 'Promise.all over per-item push()+set() calls is not atomic.',
      fix: 'Build one update() call against the parent ref with all generated keys as fields — Firebase commits multi-path updates atomically.',
      docsUrl: 'https://firebase.google.com/docs/database/web/read-and-write',
      severity: 'warning',
    },
    {
      key: 'firebase-rtdb-listener-error-not-handled',
      resultRule: 'firebase/reliability/rtdb-listener-error-not-handled',
      message: 'onValue is called with no error/cancel callback.',
      fix: 'Pass a 3rd argument to onValue (e.g. (error) => console.error(error)) so PERMISSION_DENIED and dropped connections surface.',
      docsUrl: 'https://firebase.google.com/docs/reference/js/database.md#onvalue',
      severity: 'warning',
    },
    {
      key: 'firebase-effect-deps-whole-user-object',
      resultRule: 'firebase/reliability/effect-deps-whole-user-object',
      message: 'useEffect depends on the whole user object but only reads user.uid.',
      fix: 'Depend on user?.uid instead of user — onAuthStateChanged delivers a new object reference on every token refresh even when uid is unchanged.',
      docsUrl: 'https://firebase.google.com/docs/reference/js/auth.md#onauthstatechanged',
      severity: 'warning',
    },
    {
      key: 'firebase-rtdb-write-promise-not-handled',
      resultRule: 'firebase/reliability/rtdb-write-promise-not-handled',
      message: 'A Realtime Database write promise is neither awaited in a try/catch nor .catch-handled.',
      fix: 'Wrap state-changing writes in try/catch and surface failures; do not navigate away on a write whose result was never checked.',
      docsUrl: 'https://firebase.google.com/docs/database/web/read-and-write',
      severity: 'error',
    },
    {
      key: 'firebase-firestore-rules-expired',
      resultRule: 'firebase/security/firestore-rules-expired',
      message: 'Firestore security rules contain a hard-coded expiry date that has already passed. All client reads and writes are permanently denied.',
      fix: 'Replace the timestamp.date() expiry with proper auth-based rules: allow read, write: if request.auth != null && request.auth.uid == userId;',
      docsUrl: 'https://firebase.google.com/docs/firestore/security/insecure-rules',
      severity: 'error',
    },
    {
      key: 'firebase-id-token-cookie-flags',
      resultRule: 'firebase/security/id-token-cookie-flags',
      message: 'Firebase ID token stored in a cookie without httpOnly: true.',
      fix: 'Use the Firebase Admin SDK createSessionCookie flow to issue an httpOnly, secure session cookie instead of storing raw ID tokens client-side.',
      docsUrl: 'https://firebase.google.com/docs/auth/admin/manage-cookies',
      severity: 'error',
    },
    {
      key: 'firebase-middleware-token-not-verified',
      resultRule: 'firebase/security/middleware-token-not-verified',
      message: 'Middleware reads the auth cookie but never verifies it. Any non-empty cookie value bypasses the guard.',
      fix: 'Call adminAuth.verifySessionCookie(cookie, true) in the middleware and redirect on failure.',
      docsUrl: 'https://firebase.google.com/docs/auth/admin/manage-cookies#verify_session_cookies_and_check_permissions',
      severity: 'error',
    },
    {
      key: 'firebase-hardcoded-user-id',
      resultRule: 'firebase/security/hardcoded-user-id',
      message: 'Hardcoded userId found. All users share this Firestore document.',
      fix: 'Read the userId from the authenticated user: const { user } = useAuth(); user?.uid',
      docsUrl: 'https://firebase.google.com/docs/auth/web/manage-users',
      severity: 'error',
    },
    {
      key: 'firebase-auth-user-not-found-disclosure',
      resultRule: 'firebase/security/auth-user-not-found-disclosure',
      message: 'Checking for auth/user-not-found exposes whether an email is registered (user enumeration).',
      fix: 'Show the same generic message for all auth errors regardless of the error code.',
      docsUrl: 'https://firebase.google.com/docs/auth/web/password-auth#enumeration-protection',
      severity: 'warning',
    },
    {
      key: 'firebase-signup-password-confirm',
      resultRule: 'firebase/correctness/signup-password-confirm',
      message: 'createUserWithEmailAndPassword is called without verifying password === confirmPassword.',
      fix: 'Add: if (password !== confirmPassword) { setError("Passwords do not match"); return; } before the Firebase call.',
      docsUrl: 'https://firebase.google.com/docs/auth/web/password-auth',
      severity: 'warning',
    },
    {
      key: 'firebase-use-array-union-remove',
      resultRule: 'firebase/correctness/use-array-union-remove',
      message: 'Firestore array updated with read-modify-write spread/filter instead of atomic arrayUnion/arrayRemove.',
      fix: 'Use arrayUnion(item) or arrayRemove(item) from firebase/firestore for atomic array operations.',
      docsUrl: 'https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array',
      severity: 'warning',
    },
    {
      key: 'firebase-duplicate-initialize-app',
      resultRule: 'firebase/correctness/duplicate-initialize-app',
      message: 'initializeApp() called without checking getApps() first — risk of duplicate-app crash.',
      fix: 'Use: const app = getApps().length ? getApp() : initializeApp(config);',
      docsUrl: 'https://firebase.google.com/docs/projects/multiprojects',
      severity: 'warning',
    },
    {
      key: 'firebase-onSnapshot-async-throw',
      resultRule: 'firebase/reliability/onSnapshot-async-throw',
      message: 'throw inside an async onSnapshot callback creates an unhandled promise rejection.',
      fix: 'Return with error logging instead of throwing, or provide an error callback as the third argument to onSnapshot.',
      docsUrl: 'https://firebase.google.com/docs/firestore/query-data/listen#handle_listen_errors',
      severity: 'warning',
    },
    {
      key: 'firebase-onSnapshot-missing-error-callback',
      resultRule: 'firebase/reliability/onSnapshot-missing-error-callback',
      message: 'onSnapshot called without an error callback. Firestore permission errors silently stop the listener.',
      fix: 'Add an error callback: onSnapshot(ref, successFn, (error) => { console.error(error); })',
      docsUrl: 'https://firebase.google.com/docs/firestore/query-data/listen#handle_listen_errors',
      severity: 'warning',
    },
    {
      key: 'firebase-firestore-document-size-guard',
      resultRule: 'firebase/reliability/firestore-document-size-guard',
      message: 'Firestore write includes editor.getJSON() without a document size check.',
      fix: 'Check document size before writing: if (new Blob([payload]).size > 900_000) { setSaveStatus("Document too large"); return; }',
      docsUrl: 'https://firebase.google.com/docs/firestore/quotas#limits',
      severity: 'warning',
    },
    {
      key: 'firebase-use-timestamp-now',
      resultRule: 'firebase/correctness/use-timestamp-now',
      message: 'new Date() used for a Firestore timestamp field instead of Timestamp.now() or serverTimestamp().',
      fix: 'Import { Timestamp } from "firebase/firestore" and use Timestamp.now() for consistency with Firestore security rules.',
      docsUrl: 'https://firebase.google.com/docs/reference/js/firestore_.timestamp',
      severity: 'info',
    },
  ],
};
