import type { ProviderManifest } from '../../types.js';

export const elevenlabsManifest: ProviderManifest = {
  name: 'elevenlabs',
  displayName: 'ElevenLabs',
  detect: {
    packages: ['@11labs/client', 'elevenlabs', '@elevenlabs/elevenlabs-js'],
    imports: ['@11labs/client', 'elevenlabs', '@elevenlabs/elevenlabs-js'],
    urlPatterns: ['api.elevenlabs.io'],
  },
  surface: {
    packages: ['@elevenlabs/elevenlabs-js', 'elevenlabs'],
    clientConstructors: ['ElevenLabsClient'],
    clientNamePattern: /^(eleven[-_]?labs|11labs)([-_]?client)?$/i,
    docsUrl: 'https://elevenlabs.io/docs/api-reference/introduction',
    // ElevenAPI surface only; agents/ConvAI excluded by scope decision
    // 2026-07-29. The docs nav (llms.txt breadcrumbs) splits the API
    // reference into sibling groups — ElevenAPI, ElevenAgents, ElevenCreative,
    // Core Resources, Workspace, Legacy — and this list covers the ElevenAPI
    // group's root resources: textToSpeech, speechToText, music, speechEngine,
    // voices (incl. settings/ivc/pvc/samples), textToDialogue, speechToSpeech
    // (Voice Changer), textToVoice (Voice Design), textToSoundEffects,
    // audioIsolation, dubbing, forcedAlignment, pronunciationDictionaries,
    // audioNative, plus the standalone samples client (docs: Voices > Samples).
    // Out-of-scope roots deliberately omitted: conversationalAi (ElevenAgents),
    // studio/productions (ElevenCreative), workspace/webhooks/serviceAccounts/
    // user/usage/workspaces/environmentVariables (Workspace/ElevenAgents
    // admin), history/models/tokens (Core Resources) — calls to them land in
    // unknown_sdk_calls, by design.
    // Verified against @elevenlabs/elevenlabs-js@2.59.0 (Client.d.ts root
    // getters walked into every per-resource client declaration; the exported
    // ElevenLabsClient in wrapper/ElevenLabsClient.d.ts extends the Fern base
    // and overrides music/speechToText/speechEngine/webhooks with same-surface
    // subclasses). Cross-checked against api.elevenlabs.io/openapi.json:
    // every method below maps 1:1 to a live spec endpoint (voices.search is
    // GET /v2/voices); two spec endpoints have no SDK method yet (GET
    // /v1/voices/accents, POST /v1/voices/{id}/replicate-to-isolated-
    // environment). Spec-deprecated but still-typed methods are kept because
    // real code still calls them: dubbing.resource.* (closed-beta resource
    // endpoints, docs now under Legacy), dubbing.transcript.getTranscriptForDub
    // (superseded by dubbing.transcripts.get), textToVoice.createPreviews
    // (superseded by textToVoice.design). Deliberately excluded: the root
    // fetch() passthrough (the escape hatch unknown_sdk_calls exists to
    // reveal) and the wrapper-only WebSocket helpers speechToText.realtime.
    // connect and speechEngine.attach (not derivable from the Fern resource
    // types; their use lands in unknown_sdk_calls). WebSocket-only channels
    // (TTS stream-input, STT realtime, speech-engine upstream) ship types but
    // no client methods and are not listed. Re-verify on SDK bumps
    // (`pnpm check:surface`).
    methods: [
      'audioIsolation.convert',
      'audioIsolation.delete',
      'audioIsolation.list',
      'audioIsolation.stream',
      'audioNative.create',
      'audioNative.getSettings',
      'audioNative.update',
      'audioNative.updateContentFromUrl',
      'dubbing.audio.get',
      'dubbing.create',
      'dubbing.delete',
      'dubbing.get',
      'dubbing.list',
      'dubbing.project.create',
      'dubbing.project.delete',
      'dubbing.project.get',
      'dubbing.project.language.create',
      'dubbing.project.language.delete',
      'dubbing.project.language.get',
      'dubbing.project.language.list',
      'dubbing.project.language.transcript.get',
      'dubbing.project.language.transcript.regenerate',
      'dubbing.project.language.transcript.updateSegment',
      'dubbing.project.list',
      'dubbing.project.transcript.createSegment',
      'dubbing.project.transcript.deleteSegment',
      'dubbing.project.transcript.get',
      'dubbing.project.transcript.updateSegment',
      'dubbing.resource.dub',
      'dubbing.resource.get',
      'dubbing.resource.language.add',
      'dubbing.resource.migrateSegments',
      'dubbing.resource.render',
      'dubbing.resource.segment.delete',
      'dubbing.resource.segment.update',
      'dubbing.resource.speaker.create',
      'dubbing.resource.speaker.findSimilarVoices',
      'dubbing.resource.speaker.segment.create',
      'dubbing.resource.speaker.update',
      'dubbing.resource.transcribe',
      'dubbing.resource.translate',
      'dubbing.transcript.getTranscriptForDub',
      'dubbing.transcripts.get',
      'forcedAlignment.create',
      'music.compose',
      'music.composeDetailed',
      'music.composeDetailedStream',
      'music.compositionPlan.create',
      'music.finetunes.create',
      'music.finetunes.delete',
      'music.finetunes.get',
      'music.finetunes.list',
      'music.finetunes.update',
      'music.separateStems',
      'music.stream',
      'music.upload',
      'music.videoToMusic',
      'pronunciationDictionaries.createFromFile',
      'pronunciationDictionaries.createFromRules',
      'pronunciationDictionaries.download',
      'pronunciationDictionaries.get',
      'pronunciationDictionaries.list',
      'pronunciationDictionaries.rules.add',
      'pronunciationDictionaries.rules.remove',
      'pronunciationDictionaries.rules.set',
      'pronunciationDictionaries.update',
      'samples.delete',
      'speechEngine.create',
      'speechEngine.delete',
      'speechEngine.get',
      'speechEngine.list',
      'speechEngine.update',
      'speechToSpeech.convert',
      'speechToSpeech.stream',
      'speechToText.convert',
      'speechToText.transcripts.delete',
      'speechToText.transcripts.get',
      'textToDialogue.convert',
      'textToDialogue.convertWithTimestamps',
      'textToDialogue.stream',
      'textToDialogue.streamWithTimestamps',
      'textToSoundEffects.convert',
      'textToSpeech.convert',
      'textToSpeech.convertWithTimestamps',
      'textToSpeech.stream',
      'textToSpeech.streamWithTimestamps',
      'textToVoice.create',
      'textToVoice.createPreviews',
      'textToVoice.design',
      'textToVoice.preview.stream',
      'textToVoice.remix',
      'voices.delete',
      'voices.findSimilarVoices',
      'voices.get',
      'voices.getAll',
      'voices.getShared',
      'voices.ivc.create',
      'voices.pvc.create',
      'voices.pvc.samples.audio.get',
      'voices.pvc.samples.create',
      'voices.pvc.samples.delete',
      'voices.pvc.samples.speakers.audio.get',
      'voices.pvc.samples.speakers.get',
      'voices.pvc.samples.speakers.separate',
      'voices.pvc.samples.update',
      'voices.pvc.samples.waveform.get',
      'voices.pvc.train',
      'voices.pvc.update',
      'voices.pvc.verification.captcha.get',
      'voices.pvc.verification.captcha.verify',
      'voices.pvc.verification.request',
      'voices.samples.audio.get',
      'voices.search',
      'voices.settings.get',
      'voices.settings.getDefault',
      'voices.settings.update',
      'voices.share',
      'voices.update',
    ],
  },
  rules: [
    {
      key: 'elevenlabs-validate-signed-url-response',
      resultRule: 'elevenlabs/correctness/validate-signed-url-response',
      message: 'The signed URL response is used without validating that signed_url is present.',
      fix: 'Check that data.signed_url exists before using it, and throw/return an error response if it is missing.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/api-reference/conversations/get-signed-url',
      severity: 'error',
    },
    {
      key: 'elevenlabs-no-error-object-logging',
      resultRule: 'elevenlabs/security/no-error-object-logging',
      message: 'A catch block around an ElevenLabs API call logs the raw error object.',
      fix: 'Log a sanitized message (e.g. error instanceof Error ? error.message : "Unknown error") instead of the raw error object.',
      docsUrl: 'https://elevenlabs.io/docs/api-reference/authentication',
      severity: 'error',
    },
    {
      key: 'elevenlabs-fetch-timeout-required',
      resultRule: 'elevenlabs/reliability/fetch-timeout-required',
      message: 'A fetch call to the ElevenLabs API has no abort signal/timeout.',
      fix: 'Pass an AbortController signal (e.g. via setTimeout(() => controller.abort(), 5000)) so a slow or unresponsive API does not hang the request indefinitely.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/api-reference/conversations/get-signed-url',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-validate-agent-id-format',
      resultRule: 'elevenlabs/correctness/validate-agent-id-format',
      message: 'agentId is checked for existence but not validated against an expected format.',
      fix: 'Validate agentId against an allowed pattern (e.g. /^[a-zA-Z0-9\\-]{1,64}$/) before using it in an ElevenLabs API request.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/customization/authentication',
      severity: 'error',
    },
    {
      key: 'elevenlabs-secure-session-id-generation',
      resultRule: 'elevenlabs/security/secure-session-id-generation',
      message: 'A session id is generated with Math.random(), which is not cryptographically secure.',
      fix: 'Use crypto.getRandomValues() to generate session ids instead of Math.random().',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/guides/how-to/best-practices/security',
      severity: 'error',
    },
    {
      key: 'elevenlabs-conversation-error-recovery',
      resultRule: 'elevenlabs/reliability/conversation-error-recovery',
      message: 'A loading flag set before starting a conversation is never reset on failure.',
      fix: 'Reset the loading flag in the catch block (or a finally block) so a failed attempt does not leave the UI stuck loading.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/libraries/java-script',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-api-version-pinning',
      resultRule: 'elevenlabs/reliability/api-version-pinning',
      message: 'A fetch call to the ElevenLabs API has no explicit API version header.',
      fix: 'Add an explicit version header (e.g. elevenlabs-version) to the request instead of relying on the URL path alone.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/resources/breaking-changes-policy',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-check-http-status-before-json',
      resultRule: 'elevenlabs/correctness/check-http-status-before-json',
      message: 'response.json() is called on an ElevenLabs API response without checking response.ok/status first.',
      fix: 'Check response.ok (or response.status) before calling response.json(), so an error body is not parsed as valid data.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/resources/errors',
      severity: 'error',
    },
    {
      key: 'elevenlabs-conversation-cleanup-on-error',
      resultRule: 'elevenlabs/reliability/conversation-cleanup-on-error',
      message: 'A call to end the conversation has no surrounding try/catch.',
      fix: 'Wrap conversation.endSession()/endConversation() in try/catch so a rejection does not leave the conversation state in memory.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/libraries/java-script',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-env-var-validation',
      resultRule: 'elevenlabs/correctness/env-var-validation',
      message: 'An ElevenLabs API key is only validated inside a request handler, not at module load.',
      fix: 'Read and validate the env var at module scope (and throw if missing) so a misconfigured deployment fails at startup.',
      docsUrl: 'https://elevenlabs.io/docs/api-reference/authentication',
      severity: 'warning',
    },
  ],
};
