import type { ProviderManifest } from '../../types.js';

export const elevenlabsManifest: ProviderManifest = {
  name: 'elevenlabs',
  displayName: 'ElevenLabs',
  detect: {
    packages: ['@11labs/client', 'elevenlabs', '@elevenlabs/elevenlabs-js'],
    imports: ['@11labs/client', 'elevenlabs', '@elevenlabs/elevenlabs-js'],
    urlPatterns: ['api.elevenlabs.io'],
  },
  oxlintRules: [
    {
      key: 'elevenlabs-validate-signed-url-response',
      resultRule: 'elevenlabs/correctness/validate-signed-url-response',
      message: 'The signed URL response is used without validating that signed_url is present.',
      fix: 'Check that data.signed_url exists before using it, and throw/return an error response if it is missing.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/api-reference/conversations/get-signed-url',
      severity: 'error',
    },
    {
      key: 'elevenlabs-no-error-object-logging',
      resultRule: 'elevenlabs/security/no-error-object-logging',
      message: 'A catch block around an ElevenLabs API call logs the raw error object.',
      fix: 'Log a sanitized message (e.g. error instanceof Error ? error.message : "Unknown error") instead of the raw error object.',
      docsUrl: 'https://elevenlabs.io/docs/api-reference/authentication',
      severity: 'error',
    },
    {
      key: 'elevenlabs-fetch-timeout-required',
      resultRule: 'elevenlabs/reliability/fetch-timeout-required',
      message: 'A fetch call to the ElevenLabs API has no abort signal/timeout.',
      fix: 'Pass an AbortController signal (e.g. via setTimeout(() => controller.abort(), 5000)) so a slow or unresponsive API does not hang the request indefinitely.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/api-reference/conversations/get-signed-url',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-validate-agent-id-format',
      resultRule: 'elevenlabs/correctness/validate-agent-id-format',
      message: 'agentId is checked for existence but not validated against an expected format.',
      fix: 'Validate agentId against an allowed pattern (e.g. /^[a-zA-Z0-9\\-]{1,64}$/) before using it in an ElevenLabs API request.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/customization/authentication',
      severity: 'error',
    },
    {
      key: 'elevenlabs-secure-session-id-generation',
      resultRule: 'elevenlabs/security/secure-session-id-generation',
      message: 'A session id is generated with Math.random(), which is not cryptographically secure.',
      fix: 'Use crypto.getRandomValues() to generate session ids instead of Math.random().',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/guides/how-to/best-practices/security',
      severity: 'error',
    },
    {
      key: 'elevenlabs-conversation-error-recovery',
      resultRule: 'elevenlabs/reliability/conversation-error-recovery',
      message: 'A loading flag set before starting a conversation is never reset on failure.',
      fix: 'Reset the loading flag in the catch block (or a finally block) so a failed attempt does not leave the UI stuck loading.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/libraries/java-script',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-api-version-pinning',
      resultRule: 'elevenlabs/reliability/api-version-pinning',
      message: 'A fetch call to the ElevenLabs API has no explicit API version header.',
      fix: 'Add an explicit version header (e.g. elevenlabs-version) to the request instead of relying on the URL path alone.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/resources/breaking-changes-policy',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-check-http-status-before-json',
      resultRule: 'elevenlabs/correctness/check-http-status-before-json',
      message: 'response.json() is called on an ElevenLabs API response without checking response.ok/status first.',
      fix: 'Check response.ok (or response.status) before calling response.json(), so an error body is not parsed as valid data.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-api/resources/errors',
      severity: 'error',
    },
    {
      key: 'elevenlabs-conversation-cleanup-on-error',
      resultRule: 'elevenlabs/reliability/conversation-cleanup-on-error',
      message: 'A call to end the conversation has no surrounding try/catch.',
      fix: 'Wrap conversation.endSession()/endConversation() in try/catch so a rejection does not leave the conversation state in memory.',
      docsUrl: 'https://elevenlabs.io/docs/eleven-agents/libraries/java-script',
      severity: 'warning',
    },
    {
      key: 'elevenlabs-env-var-validation',
      resultRule: 'elevenlabs/correctness/env-var-validation',
      message: 'An ElevenLabs API key is only validated inside a request handler, not at module load.',
      fix: 'Read and validate the env var at module scope (and throw if missing) so a misconfigured deployment fails at startup.',
      docsUrl: 'https://elevenlabs.io/docs/api-reference/authentication',
      severity: 'warning',
    },
  ],
};
