import type { ProviderManifest } from '../../types.js';

export const supabaseManifest: ProviderManifest = {
  name: 'supabase',
  displayName: 'Supabase',
  detect: {
    packages: ['@supabase/supabase-js'],
    imports: ['@supabase/supabase-js', '@supabase/ssr'],
    urlPatterns: ['supabase.co'],
  },
  oxlintRules: [
    {
      key: 'supabase-scope-queries-by-tenant-column',
      resultRule: 'supabase/correctness/scope-queries-by-tenant-column',
      message: 'Query selects a tenant column but never filters by it.',
      fix: 'Add .eq("<column>", value) (or .match()/.filter()) to scope results to the caller. If RLS scopes this table the filter is still worth adding — defense-in-depth, and it avoids overfetching.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/eq',
      severity: 'warning',
    },
    {
      key: 'supabase-validate-uuid-columns',
      resultRule: 'supabase/correctness/validate-uuid-columns',
      message: 'Value passed to a uuid-typed column is only checked with typeof === "string".',
      fix: 'Validate UUID shape with a regex (e.g. /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i) before insert/upsert.',
      docsUrl: 'https://supabase.com/docs/guides/database/tables#data-types',
      severity: 'info',
    },
    {
      key: 'supabase-order-by-timestamp-not-identity',
      resultRule: 'supabase/correctness/order-by-timestamp-not-identity',
      message: 'Query orders by "id" instead of a selected timestamp column.',
      fix: 'Order by the timestamp column (e.g. .order("created_at", { ascending: false })) instead of the surrogate key.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/order',
      severity: 'info',
    },
    {
      key: 'supabase-consistent-input-length-limits',
      resultRule: 'supabase/correctness/consistent-input-length-limits',
      message: 'A sibling string field in this insert has no length cap, unlike the others.',
      fix: 'Apply the same length cap pattern used for the other fields, e.g. field.length > 2000.',
      docsUrl: 'https://supabase.com/docs/guides/database/tables',
      severity: 'warning',
    },
    {
      key: 'supabase-idempotent-mutations',
      resultRule: 'supabase/reliability/idempotent-mutations',
      message: 'Insert payload has no unique/idempotency key field, so a retried request can create a duplicate row.',
      fix: 'Include a client-generated unique key (e.g. an id or *_key field backed by a unique constraint), or use .upsert(..., { onConflict: "<key column>" }).',
      docsUrl: 'https://supabase.com/docs/reference/javascript/upsert',
      severity: 'info',
    },
    {
      key: 'supabase-fail-fast-env-validation',
      resultRule: 'supabase/reliability/fail-fast-env-validation',
      message: 'createClient is called with env vars that have no presence check.',
      fix: 'Throw an error naming the env var (e.g. if (!url || !key) throw new Error("SUPABASE_URL/KEY must be set")) before creating the client — the SDK\'s own error ("supabaseKey is required.") does not say which variable to fix.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/initializing',
      severity: 'info',
    },
    {
      key: 'supabase-no-user-metadata-authz',
      resultRule: 'supabase/security/no-user-metadata-authz',
      message: 'Authorization data is read from or written to user_metadata, which clients can modify.',
      fix: 'Store roles in app_metadata via a trusted server path, or in an RLS-protected profiles table — never user_metadata.',
      docsUrl: 'https://supabase.com/docs/guides/auth/users',
      severity: 'error',
    },
    {
      key: 'supabase-single-without-error-check',
      resultRule: 'supabase/correctness/single-without-error-check',
      message: 'A .single() query ignores the returned error field.',
      fix: 'Destructure and check error, or use .maybeSingle() and handle a missing row explicitly.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/single',
      severity: 'warning',
    },
    {
      key: 'supabase-non-atomic-replace-pattern',
      resultRule: 'supabase/correctness/non-atomic-replace-pattern',
      message: 'Child rows are replaced via delete-then-insert without checking errors.',
      fix: 'Wrap delete+insert in a Postgres RPC (single transaction) and surface error from each step.',
      docsUrl: 'https://supabase.com/docs/guides/database/functions',
      severity: 'warning',
    },
    {
      key: 'supabase-unchecked-mutation-error',
      resultRule: 'supabase/correctness/unchecked-mutation-error',
      message: 'A Supabase insert/update/delete never checks the returned error field.',
      fix: 'Destructure { error } from every mutation and revert optimistic UI or show a toast on failure.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/insert',
      severity: 'warning',
    },
    {
      key: 'supabase-realtime-missing-filter',
      resultRule: 'supabase/reliability/realtime-missing-filter',
      message: 'A Realtime postgres_changes subscription listens to an entire table with no filter.',
      fix: 'Add a filter option scoped to the current user (e.g. filter: `receiver_id=eq.${user.id}`).',
      docsUrl: 'https://supabase.com/docs/guides/realtime/postgres-changes#filtering',
      severity: 'error',
    },
    {
      key: 'supabase-storage-error-not-surfaced',
      resultRule: 'supabase/reliability/storage-error-not-surfaced',
      message: 'A storage upload failure is ignored and execution continues.',
      fix: 'On uploadError, stop and show an error instead of saving a stale URL.',
      docsUrl: 'https://supabase.com/docs/reference/javascript/storage-from-upload',
      severity: 'warning',
    },
  ],
};
