import type { ProviderManifest } from '../../types.js';

export const auth0Manifest: ProviderManifest = {
  name: 'auth0',
  displayName: 'Auth0',
  detect: {
    // `auth0` (node-auth0): without it, an SDK-only repo was detected via the
    // URL pattern alone, which disables coverage by design (url-only gate).
    packages: ['jsonwebtoken', 'jwks-rsa', 'express-jwt', 'auth0'],
    imports: ['jsonwebtoken', 'jwks-rsa', 'express-jwt', 'auth0'],
    urlPatterns: ['auth0.com'],
  },
  surface: {
    packages: ['auth0', 'auth0/management'],
    clientConstructors: ['ManagementClient', 'AuthenticationClient', 'UserInfoClient'],
    clientNamePattern: /^auth0([-_]?client)?$/i,
    docsUrl: 'https://auth0.com/docs/api',
    // The SDK revision this surface was last read against by hand. Bump both
    // together, only after re-reading the diff — `pnpm sdk:watch` lists every
    // source commit landed since `commit`, including the logic changes that
    // leave the method list untouched.
    verified: {
      version: '6.3.0',
      commit: 'f9d641348a39b5203a59a445e8bff2c094eadaee',
      at: '2026-08-19',
      sourceDir: 'src',
    },
    // Verified against auth0@6.3.0 (node-auth0, Fern-generated) published type
    // declarations: ManagementClient resource getters walked from
    // dist/cjs/management/Client.d.ts (the exported wrapper in
    // wrapper/ManagementClient.d.ts extends it without adding resources),
    // AuthenticationClient resource properties from dist/cjs/auth/index.d.ts
    // (database/oauth/passwordless classes plus the IBackchannel and
    // ICustomTokenExchange interfaces), and UserInfoClient from
    // dist/cjs/userinfo/index.d.ts. Completeness cross-checked against the
    // Fern-generated reference.md shipped in the same package: all 444
    // Management paths match 1:1 in both directions; the remaining 18 entries
    // are the Authentication API client (database.*, oauth.*, passwordless.*,
    // backchannel.*, tokenExchange.*) and UserInfoClient.getUserInfo, which
    // reference.md does not document — each read directly from the auth/
    // userinfo declaration files. Deliberately excluded: ManagementClient
    // .fetch (passthrough transport escape hatch — must land in
    // unknown_sdk_calls) and oauth.idTokenValidator.validate (readonly
    // internal ID-token helper, not documented API surface). The
    // 'auth0/legacy' subpath (re-export of the auth0-legacy v4-style SDK) and
    // the MyAccount / MyOrganization APIs (no client in this SDK) are out of
    // scope. Added in 6.2.0, all plain additions read from the SDK source:
    // the agents.* namespace (/agents CRUD), organizations.clients.*
    // (/organizations/{id}/clients), organizations.roles.groups.list, and
    // connections.directoryProvisioning.add/deleteSynchronizedGroupSelections
    // (POST/DELETE on the existing synchronized-groups path). Added in 6.3.0:
    // keys.networkAcls.list/create (GET/POST /keys/network-acls) and .get
    // (GET /keys/network-acls/{id}).
    //
    // Read for 6.3.0 beyond the method list: flows.* and forms.* now throw
    // typed errors where those statuses previously fell through to the generic
    // handler — ConflictError on 409 (flows, flows.executions) and
    // BadRequestError on 400 (forms). Same signatures, different runtime
    // behaviour for a caller matching on error type; no method changed, so
    // nothing here alters the list. Not a removal or rename, so no
    // compatibility.ts entry.
    // Re-verify on SDK majors (`pnpm check:surface`).
    methods: [
      'actions.create',
      'actions.delete',
      'actions.deploy',
      'actions.executions.get',
      'actions.get',
      'actions.list',
      'actions.modules.create',
      'actions.modules.delete',
      'actions.modules.get',
      'actions.modules.list',
      'actions.modules.listActions',
      'actions.modules.rollback',
      'actions.modules.update',
      'actions.modules.versions.create',
      'actions.modules.versions.get',
      'actions.modules.versions.list',
      'actions.test',
      'actions.triggers.bindings.list',
      'actions.triggers.bindings.updateMany',
      'actions.triggers.list',
      'actions.update',
      'actions.versions.deploy',
      'actions.versions.get',
      'actions.versions.list',
      'agents.create',
      'agents.delete',
      'agents.list',
      'agents.read',
      'agents.update',
      'anomaly.blocks.checkIp',
      'anomaly.blocks.unblockIp',
      'attackProtection.botDetection.get',
      'attackProtection.botDetection.update',
      'attackProtection.breachedPasswordDetection.get',
      'attackProtection.breachedPasswordDetection.update',
      'attackProtection.bruteForceProtection.get',
      'attackProtection.bruteForceProtection.update',
      'attackProtection.captcha.get',
      'attackProtection.captcha.update',
      'attackProtection.phoneProviderProtection.get',
      'attackProtection.phoneProviderProtection.patch',
      'attackProtection.suspiciousIpThrottling.get',
      'attackProtection.suspiciousIpThrottling.update',
      'backchannel.authorize',
      'backchannel.backchannelGrant',
      'branding.get',
      'branding.phone.providers.create',
      'branding.phone.providers.delete',
      'branding.phone.providers.get',
      'branding.phone.providers.list',
      'branding.phone.providers.test',
      'branding.phone.providers.update',
      'branding.phone.templates.create',
      'branding.phone.templates.delete',
      'branding.phone.templates.get',
      'branding.phone.templates.list',
      'branding.phone.templates.reset',
      'branding.phone.templates.test',
      'branding.phone.templates.update',
      'branding.templates.deleteUniversalLogin',
      'branding.templates.getUniversalLogin',
      'branding.templates.updateUniversalLogin',
      'branding.themes.create',
      'branding.themes.delete',
      'branding.themes.get',
      'branding.themes.getDefault',
      'branding.themes.update',
      'branding.update',
      'clientGrants.create',
      'clientGrants.delete',
      'clientGrants.get',
      'clientGrants.list',
      'clientGrants.organizations.list',
      'clientGrants.update',
      'clients.connections.get',
      'clients.create',
      'clients.credentials.create',
      'clients.credentials.delete',
      'clients.credentials.get',
      'clients.credentials.list',
      'clients.credentials.update',
      'clients.delete',
      'clients.get',
      'clients.list',
      'clients.previewCimdMetadata',
      'clients.registerCimdClient',
      'clients.rotateSecret',
      'clients.update',
      'connectionProfiles.create',
      'connectionProfiles.delete',
      'connectionProfiles.get',
      'connectionProfiles.getTemplate',
      'connectionProfiles.list',
      'connectionProfiles.listTemplates',
      'connectionProfiles.update',
      'connections.checkStatus',
      'connections.clients.get',
      'connections.clients.update',
      'connections.create',
      'connections.delete',
      'connections.directoryProvisioning.addSynchronizedGroupSelections',
      'connections.directoryProvisioning.create',
      'connections.directoryProvisioning.delete',
      'connections.directoryProvisioning.deleteSynchronizedGroupSelections',
      'connections.directoryProvisioning.get',
      'connections.directoryProvisioning.getDefaultMapping',
      'connections.directoryProvisioning.list',
      'connections.directoryProvisioning.listSynchronizedGroups',
      'connections.directoryProvisioning.set',
      'connections.directoryProvisioning.synchronizations.create',
      'connections.directoryProvisioning.update',
      'connections.get',
      'connections.keys.create',
      'connections.keys.get',
      'connections.keys.rotate',
      'connections.list',
      'connections.scimConfiguration.create',
      'connections.scimConfiguration.delete',
      'connections.scimConfiguration.get',
      'connections.scimConfiguration.getDefaultMapping',
      'connections.scimConfiguration.list',
      'connections.scimConfiguration.tokens.create',
      'connections.scimConfiguration.tokens.delete',
      'connections.scimConfiguration.tokens.get',
      'connections.scimConfiguration.update',
      'connections.update',
      'connections.users.deleteByEmail',
      'customDomains.create',
      'customDomains.delete',
      'customDomains.get',
      'customDomains.getDefault',
      'customDomains.list',
      'customDomains.setDefault',
      'customDomains.test',
      'customDomains.update',
      'customDomains.verify',
      'database.changePassword',
      'database.signUp',
      'deviceCredentials.createPublicKey',
      'deviceCredentials.delete',
      'deviceCredentials.list',
      'emails.provider.create',
      'emails.provider.delete',
      'emails.provider.get',
      'emails.provider.update',
      'emailTemplates.create',
      'emailTemplates.get',
      'emailTemplates.set',
      'emailTemplates.update',
      'events.subscribe',
      'eventStreams.create',
      'eventStreams.delete',
      'eventStreams.deliveries.getHistory',
      'eventStreams.deliveries.list',
      'eventStreams.get',
      'eventStreams.list',
      'eventStreams.redeliveries.create',
      'eventStreams.redeliveries.createById',
      'eventStreams.test',
      'eventStreams.update',
      'flows.create',
      'flows.delete',
      'flows.executions.delete',
      'flows.executions.get',
      'flows.executions.list',
      'flows.get',
      'flows.list',
      'flows.update',
      'flows.vault.connections.create',
      'flows.vault.connections.delete',
      'flows.vault.connections.get',
      'flows.vault.connections.list',
      'flows.vault.connections.update',
      'forms.create',
      'forms.delete',
      'forms.get',
      'forms.list',
      'forms.update',
      'getUserInfo',
      'groups.delete',
      'groups.get',
      'groups.list',
      'groups.members.get',
      'groups.roles.create',
      'groups.roles.delete',
      'groups.roles.list',
      'guardian.enrollments.createTicket',
      'guardian.enrollments.delete',
      'guardian.enrollments.get',
      'guardian.factors.duo.settings.get',
      'guardian.factors.duo.settings.set',
      'guardian.factors.duo.settings.update',
      'guardian.factors.list',
      'guardian.factors.phone.getMessageTypes',
      'guardian.factors.phone.getSelectedProvider',
      'guardian.factors.phone.getTemplates',
      'guardian.factors.phone.getTwilioProvider',
      'guardian.factors.phone.setMessageTypes',
      'guardian.factors.phone.setProvider',
      'guardian.factors.phone.setTemplates',
      'guardian.factors.phone.setTwilioProvider',
      'guardian.factors.pushNotification.getApnsProvider',
      'guardian.factors.pushNotification.getSelectedProvider',
      'guardian.factors.pushNotification.getSnsProvider',
      'guardian.factors.pushNotification.setApnsProvider',
      'guardian.factors.pushNotification.setFcmProvider',
      'guardian.factors.pushNotification.setFcmv1Provider',
      'guardian.factors.pushNotification.setProvider',
      'guardian.factors.pushNotification.setSnsProvider',
      'guardian.factors.pushNotification.updateApnsProvider',
      'guardian.factors.pushNotification.updateFcmProvider',
      'guardian.factors.pushNotification.updateFcmv1Provider',
      'guardian.factors.pushNotification.updateSnsProvider',
      'guardian.factors.set',
      'guardian.factors.sms.getSelectedProvider',
      'guardian.factors.sms.getTemplates',
      'guardian.factors.sms.getTwilioProvider',
      'guardian.factors.sms.setProvider',
      'guardian.factors.sms.setTemplates',
      'guardian.factors.sms.setTwilioProvider',
      'guardian.policies.list',
      'guardian.policies.set',
      'hooks.create',
      'hooks.delete',
      'hooks.get',
      'hooks.list',
      'hooks.secrets.create',
      'hooks.secrets.delete',
      'hooks.secrets.get',
      'hooks.secrets.update',
      'hooks.update',
      'jobs.errors.get',
      'jobs.get',
      'jobs.usersExports.create',
      'jobs.usersImports.create',
      'jobs.verificationEmail.create',
      'keys.customSigning.delete',
      'keys.customSigning.get',
      'keys.customSigning.set',
      'keys.encryption.create',
      'keys.encryption.createPublicWrappingKey',
      'keys.encryption.delete',
      'keys.encryption.get',
      'keys.encryption.import',
      'keys.encryption.list',
      'keys.encryption.rekey',
      'keys.networkAcls.create',
      'keys.networkAcls.get',
      'keys.networkAcls.list',
      'keys.signing.get',
      'keys.signing.list',
      'keys.signing.revoke',
      'keys.signing.rotate',
      'logs.get',
      'logs.list',
      'logStreams.create',
      'logStreams.delete',
      'logStreams.get',
      'logStreams.list',
      'logStreams.update',
      'networkAcls.create',
      'networkAcls.delete',
      'networkAcls.get',
      'networkAcls.list',
      'networkAcls.set',
      'networkAcls.update',
      'oauth.authorizationCodeGrant',
      'oauth.authorizationCodeGrantWithPKCE',
      'oauth.clientCredentialsGrant',
      'oauth.passwordGrant',
      'oauth.pushedAuthorization',
      'oauth.refreshTokenGrant',
      'oauth.revokeRefreshToken',
      'oauth.tokenForConnection',
      'organizations.clientGrants.create',
      'organizations.clientGrants.delete',
      'organizations.clientGrants.list',
      'organizations.clients.create',
      'organizations.clients.delete',
      'organizations.clients.get',
      'organizations.clients.list',
      'organizations.clients.update',
      'organizations.connections.create',
      'organizations.connections.delete',
      'organizations.connections.get',
      'organizations.connections.list',
      'organizations.connections.update',
      'organizations.create',
      'organizations.delete',
      'organizations.discoveryDomains.create',
      'organizations.discoveryDomains.delete',
      'organizations.discoveryDomains.get',
      'organizations.discoveryDomains.getByName',
      'organizations.discoveryDomains.list',
      'organizations.discoveryDomains.update',
      'organizations.enabledConnections.add',
      'organizations.enabledConnections.delete',
      'organizations.enabledConnections.get',
      'organizations.enabledConnections.list',
      'organizations.enabledConnections.update',
      'organizations.get',
      'organizations.getByName',
      'organizations.groups.list',
      'organizations.groups.roles.create',
      'organizations.groups.roles.delete',
      'organizations.groups.roles.list',
      'organizations.invitations.create',
      'organizations.invitations.delete',
      'organizations.invitations.get',
      'organizations.invitations.list',
      'organizations.list',
      'organizations.members.create',
      'organizations.members.delete',
      'organizations.members.effectiveRoles.list',
      'organizations.members.effectiveRoles.sources.groups.list',
      'organizations.members.list',
      'organizations.members.roles.assign',
      'organizations.members.roles.delete',
      'organizations.members.roles.list',
      'organizations.roles.groups.list',
      'organizations.roles.members.list',
      'organizations.update',
      'passwordless.loginWithEmail',
      'passwordless.loginWithSMS',
      'passwordless.sendEmail',
      'passwordless.sendSMS',
      'prompts.customText.get',
      'prompts.customText.set',
      'prompts.getSettings',
      'prompts.partials.get',
      'prompts.partials.set',
      'prompts.rendering.bulkUpdate',
      'prompts.rendering.get',
      'prompts.rendering.list',
      'prompts.rendering.update',
      'prompts.updateSettings',
      'rateLimitPolicies.create',
      'rateLimitPolicies.delete',
      'rateLimitPolicies.get',
      'rateLimitPolicies.list',
      'rateLimitPolicies.update',
      'refreshTokens.delete',
      'refreshTokens.get',
      'refreshTokens.list',
      'refreshTokens.revoke',
      'refreshTokens.update',
      'resourceServers.create',
      'resourceServers.delete',
      'resourceServers.get',
      'resourceServers.list',
      'resourceServers.update',
      'riskAssessments.settings.get',
      'riskAssessments.settings.newDevice.get',
      'riskAssessments.settings.newDevice.update',
      'riskAssessments.settings.update',
      'roles.create',
      'roles.delete',
      'roles.get',
      'roles.groups.create',
      'roles.groups.delete',
      'roles.groups.get',
      'roles.list',
      'roles.permissions.add',
      'roles.permissions.delete',
      'roles.permissions.list',
      'roles.update',
      'roles.users.assign',
      'roles.users.list',
      'rules.create',
      'rules.delete',
      'rules.get',
      'rules.list',
      'rules.update',
      'rulesConfigs.delete',
      'rulesConfigs.list',
      'rulesConfigs.set',
      'selfServiceProfiles.create',
      'selfServiceProfiles.customText.list',
      'selfServiceProfiles.customText.set',
      'selfServiceProfiles.delete',
      'selfServiceProfiles.get',
      'selfServiceProfiles.list',
      'selfServiceProfiles.ssoTicket.create',
      'selfServiceProfiles.ssoTicket.revoke',
      'selfServiceProfiles.update',
      'sessions.delete',
      'sessions.get',
      'sessions.revoke',
      'sessions.update',
      'stats.getActiveUsersCount',
      'stats.getDaily',
      'supplementalSignals.get',
      'supplementalSignals.patch',
      'tenants.settings.get',
      'tenants.settings.update',
      'tickets.changePassword',
      'tickets.verifyEmail',
      'tokenExchange.exchangeToken',
      'tokenExchangeProfiles.create',
      'tokenExchangeProfiles.delete',
      'tokenExchangeProfiles.get',
      'tokenExchangeProfiles.list',
      'tokenExchangeProfiles.update',
      'userAttributeProfiles.create',
      'userAttributeProfiles.delete',
      'userAttributeProfiles.get',
      'userAttributeProfiles.getTemplate',
      'userAttributeProfiles.list',
      'userAttributeProfiles.listTemplates',
      'userAttributeProfiles.update',
      'userBlocks.delete',
      'userBlocks.deleteByIdentifier',
      'userBlocks.list',
      'userBlocks.listByIdentifier',
      'userGrants.delete',
      'userGrants.deleteByUserId',
      'userGrants.list',
      'users.authenticationMethods.create',
      'users.authenticationMethods.delete',
      'users.authenticationMethods.deleteAll',
      'users.authenticationMethods.get',
      'users.authenticationMethods.list',
      'users.authenticationMethods.set',
      'users.authenticationMethods.update',
      'users.authenticators.deleteAll',
      'users.connectedAccounts.list',
      'users.create',
      'users.delete',
      'users.effectivePermissions.list',
      'users.effectivePermissions.sources.roles.list',
      'users.effectiveRoles.list',
      'users.effectiveRoles.sources.groups.list',
      'users.enrollments.get',
      'users.get',
      'users.groups.get',
      'users.identities.delete',
      'users.identities.link',
      'users.list',
      'users.listUsersByEmail',
      'users.logs.list',
      'users.multifactor.deleteProvider',
      'users.multifactor.invalidateRememberBrowser',
      'users.organizations.list',
      'users.permissions.create',
      'users.permissions.delete',
      'users.permissions.list',
      'users.refreshToken.delete',
      'users.refreshToken.list',
      'users.regenerateRecoveryCode',
      'users.revokeAccess',
      'users.riskAssessments.clear',
      'users.roles.assign',
      'users.roles.delete',
      'users.roles.list',
      'users.sessions.delete',
      'users.sessions.list',
      'users.update',
      'verifiableCredentials.verification.templates.create',
      'verifiableCredentials.verification.templates.delete',
      'verifiableCredentials.verification.templates.get',
      'verifiableCredentials.verification.templates.list',
      'verifiableCredentials.verification.templates.update',
    ],
  },
  rules: [
    {
      key: 'auth0-required-audience-validation',
      resultRule: 'auth0/security/required-audience-validation',
      message:
        'Auth0 JWT verification is configured without (or only conditionally with) audience validation.',
      fix: 'Require AUTH0_AUDIENCE and fail closed if it is unset, then always pass `audience` to jwt.verify()/express-jwt so a token issued for a different API cannot authenticate here.',
      docsUrl: 'https://auth0.com/docs/secure/tokens/json-web-tokens/validate-json-web-tokens',
      severity: 'error',
    },
    {
      key: 'auth0-no-account-link-without-verified-email',
      resultRule: 'auth0/security/no-account-link-without-verified-email',
      message:
        'Account lookup is keyed on an email claim without checking email_verified first.',
      fix: 'Require claims.email_verified (or the namespaced equivalent) before using the email claim to look up or re-link an existing account; otherwise create a new, unlinked account.',
      docsUrl: 'https://auth0.com/docs/manage-users/user-accounts/user-account-linking',
      severity: 'error',
    },
    {
      key: 'auth0-dead-claim-verification-check',
      resultRule: 'auth0/correctness/dead-claim-verification-check',
      message: 'Stringified boolean claim is checked with .includes() against a substring it can never contain.',
      fix: 'Compare the claim directly, e.g. `if (!claims.email_verified) { ... }`, instead of stringifying it and checking for a substring.',
      docsUrl: 'https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims',
      severity: 'error',
    },
    {
      key: 'auth0-jwks-refresh-on-unknown-kid',
      resultRule: 'auth0/reliability/jwks-refresh-on-unknown-kid',
      message: 'JWKS kid lookup has no retry-with-forced-refresh path on a cache miss.',
      fix: 'On a kid miss, force a fresh JWKS fetch and retry the lookup once before failing, instead of failing immediately against a possibly-stale cache.',
      docsUrl: 'https://auth0.com/docs/get-started/tenant-settings/signing-keys/rotate-signing-keys',
      severity: 'warning',
    },
  ],
};
